### ISSUE TITLE
能正常运行项目，但一直处于运行状态，不出现弹框

### ISSUE THREAD

**Issue by silencesmile** [AirtestProject/iOS-Tagent#10]
能正常运行项目，但一直处于运行状态，不出现弹框？
Xcode：10.1
手机：6s
iOS系统：12.0.1

一直处于运行状态，很长时间以后报错，不会出现弹框

**Comment by brantxiong** [comment]
是正常的，这个是Test模式。手机上出现WebDriverAgent应用就是对的，可以启动iproxy，用AirtestIDE连接试试
