### ISSUE TITLE
连接iOS设备失败

### ISSUE THREAD

**Issue by appp-deng** [AirtestProject/iOS-Tagent#100]
ide版本：1.2.2
更新xcode版本：11.1
在ide通过http://127.0.0.1:8100 连接模拟器提示连接iOS设备失败，iOS Screen黑屏，请问需要怎么设置才能正常连接？

**Comment by EraChen233** [comment]
iOS-Tagent 已更新，支持最新版xcode 11

**Comment by zuiqingfengyang** [comment]
OS-Tagent 支持最新版xcode 11使用起来经常重新链接卡的要死简直没法哟名

**Comment by zuiqingfengyang** [comment]
xcode11.4  airtest1.2.6    iOS-Tagent下载master的实在用着让人欲哭无泪
