### ISSUE TITLE
ｉｏｓ１３是否可以兼容

### ISSUE THREAD

**Issue by dawsonBB** [AirtestProject/iOS-Tagent#102]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
*Feature

**描述问题bug**
*IOS13 的APP，airtest的IDE暂时不能进行操作，是iOS-Tagent文件还未能兼容吗

**相关截图**

**复现步骤**

**预期效果**

**Comment by EraChen233** [comment]
iOS-Tagent 已更新，支持最新版xcode 11
