### ISSUE TITLE
iphone 6p在http://127.0.0.1:8100/inspector只能看到部分屏幕投影，iPhone 5设备看到的是白屏。辛苦帮忙看下～

### ISSUE THREAD

**Issue by luoting0323** [AirtestProject/iOS-Tagent#105]
![image](https://user-images.githubusercontent.com/56343996/66699498-02989f00-ed1a-11e9-97fc-14c67b612881.png)

**Comment by EraChen233** [comment]
换xcode 10.1

**Comment by EraChen233** [comment]
iOS-Tagent 已更新，修复了这个问题，并且支持最新版xcode 11
