### ISSUE TITLE
 OpenURL WDAError: WDAError(status=13, value=Failed to open bundle://cmd/profile)

### ISSUE THREAD

**Issue by Solganis** [AirtestProject/iOS-Tagent#108]
Hello! :) Is it possible to open (deep)links in iOS?

- When I try to, the error appears - WDAError: WDAError(status=13, value=Failed to open randombundle://cmd/profile/ 

Any ideas?

- Code to execute: 
`connect_device("ios:///127.0.0.1:8100")
sleep(5)
G.DEVICE.session.open_url("randombundle://cmd/profile")`

Xcode: 10.2

**Comment by EraChen233** [comment]
Source code of open_url can be found here
https://github.com/openatx/facebook-wda/blob/master/wda/__init__.py#L604

Forgive me, but I still don't know why you want to open the URL " randombundle:// cmd / profile".  
What do you want to do?

**Comment by Solganis** [comment]
@EraChen233 thanks for answer!
The method itself is working, link is sent, but there is no activation on the real iOS device.

I'm trying to open deeplink like "appbundle://cmd/profile" to evade pressing a lot of buttons to get to the "Profile" inside my Unity app. if I decide to make every step like "press this button -> next -> next -> next" then, one full test would be taking like 5 hours or so. I'm trying to sent and open deeplinks on the real iOS device. :)

**Comment by EraChen233** [comment]
I am sorry but this is not supported.

**Comment by Solganis** [comment]
@EraChen233 thanks!

But what is the limiting factor? iOS restrictions?

**Comment by EraChen233** [comment]
We have not implemented the relevant functions.
Wda starts a server to handle the http request that Airtest sends via interface open_url. 
Only the url implemented in wda can be successfully accessed.

**Comment by EraChen233** [comment]
Thanks, you're very kind

**Comment by Solganis** [comment]
The most perfect solution we was yet to found is this. Maybe, it's gonna help someone too - `G.DEVICE.driver.session('com.apple.mobilesafari', ['-u', deeplink])`
then, you can tap to "Open" and proceed to you'r app.

Before, we was using
`adress_textedit = wait(resources_ios.safari["adress_textedit"], timeout=10, interval=0.3)
  touch(adress_textedit)
  text(deeplink)`

So, we saved about 30-50 seconds in each case.

I guess, it's nice.
