### ISSUE TITLE
Screen of iOS 13+ devices is displayed misplaced.

### ISSUE THREAD

**Issue by xd2006** [AirtestProject/iOS-Tagent#110]
Screen from devices based on iOs 13+ is dicplayed misplaced so needed elements can't be touched. 
Hidden part of the screen is marked with red arrows on the 

screenshot.

![IncorrectImage_001](https://user-images.githubusercontent.com/6172381/66855576-35e26480-ef8c-11e9-9dd4-e767495096e0.png)

**airtest version:** `1.0.22`

 - Device: iPhoneXS, XR, XSMAX
 - OS: iOs 13.1.2, 13.0
 - XCode: 10.3

**Comment by xd2006** [comment]
The same behavioir on Xcode 10.2. The key is iOs version - 13. On 12 all is OK.

**Comment by EraChen233** [comment]
Thanks for feedback. 
iOS >= 13 and Xcode>10.2 will be supported in next release.

**Comment by zhangdongjia** [comment]
> Thanks for feedback.
> iOS >= 13 and Xcode>10.2 will be supported in next release.

When will the next update be released?

**Comment by EraChen233** [comment]
It is hard to say.

**Comment by EraChen233** [comment]
iOS-Tagnet has been updated, support xcode 11.
@zhangdongjia @xd2006
