### ISSUE TITLE
iphone 12 & xcode10.3 无法在airtestIDE中连接

### ISSUE THREAD

**Issue by wyxy2005** [AirtestProject/iOS-Tagent#111]
iphone 12 & xcode10.3 无法在airtestIDE中连接,chrome访问http://127.0.0.1:8100/status和http://127.0.0.1:8100/inspector 都正常，但是用airtestIDE connect "http://127.0.0.1:8100" 
log View显示：
None
Failed to connect iOS device, please read [Docs](http://airtest.netease.com/docs/en/1_online_help/Connecting_iOS.html)

之前以为是xcode11的问题，换成了10.3也不行

**Comment by EraChen233** [comment]
iOS-Tagent 不支持 xcode >10.2

**Comment by wang542413041** [comment]
> iOS-Tagent 不支持 xcode >10.2

Xcode10.2也会出现这个问题
None
连接iOS设备失败，请查阅官网[FAQ](http://airtest.netease.com/docs/cn/2_device_connection/4_ios_connection.html)获得更多信息。

**Comment by EraChen233** [comment]
10.2是什么情况呢？可以麻烦具体描述一下么

**Comment by wang542413041** [comment]
> 10.2是什么情况呢？可以麻烦具体描述一下么

🤩，您回复的好快；

XCode10.2
iOS12.4
Airtest IDE 1.2.2

http://127.0.0.1:8100/status
http://127.0.0.1:8100/inspector
执行到这两个网站都可以正常打开和预览，
接着打开airtest 连接iOS设备，
提示：None
连接iOS设备失败，请查阅官网[FAQ](http://airtest.netease.com/docs/cn/2_device_connection/4_ios_connection.html)获得更多信息。

终端信息：
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 5 (serial:xxxx), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable


xcode10.2 log
2019-10-24 15:17:18.458011+0800 WebDriverAgentRunner-Runner[5636:1360080] -[XCUIApplication resolve]: unrecognized selector sent to instance

**Comment by moruofan** [comment]
我也遇到了上面的问题，按这个顺序还是无法连上iOS
提示：None
连接iOS设备失败，请查阅官网FAQ获得更多信息。
终端报错
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 1 (serial: 288c606949f212816f534eabca09cdc7aa210f0f), port 8100
run_ctos_loop: fd = 8
run_stoc_loop: fd = 8
recv failed: Resource temporarily unavailable
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
xcode报错：
2019-10-30 19:29:21.250686+0800 WebDriverAgentRunner-Runner[58176:9242851] -[XCApplicationQuery elementSnapshotForDebugDescription]: unrecognized selector sent to instance 0x280779320
    t =   174.70s Find the Application 'com.apple.springboard'
    t =   174.71s     Requesting snapshot of accessibility hierarchy for app with pid 56963
2019-10-30 19:29:30.106304+0800 WebDriverAgentRunner-Runner[58176:9242851] -[XCUIApplication resolve]: unrecognized selector sent to instance 0x2808653b0

**Comment by wang542413041** [comment]
尝试使用老版本Xcode了么

**Comment by xuhanping99** [comment]
> 尝试使用老版本Xcode了么

我也遇到了同样的问题，我装的Xcode版本是10.2.1，python版本是3.7，iOS设备系统是iOS12.3
我的问题是
http://127.0.0.1:8100/status
http://127.0.0.1:8100/inspector
这两个网站都可以正常打开和预览，
打开airtest 连接iOS设备，也能正常连接能看到预览

但是终端里一直报错：
waiting for connection
Number of available devices == 2
Requesting connecion to device handle == 57 (serial: 00008020-001E69A936F8002E), port 8100
run_ctos_loop: fd = 6
run_stoc_loop: fd = 6
recv failed: Resource temporarily unavailable
recv failed: Resource temporarily unavailable

**Comment by EraChen233** [comment]
iOS-Tagent 已更新，支持最新版xcode 11
@xuhanping99  @moruofan @wang542413041 @wyxy2005

**Comment by forrest1g** [comment]
求支持 XCode13.3. 我Airtest IDE 还是连不上设备。
http://127.0.0.1:8100/status 正常
