### ISSUE TITLE
None Failed to connect iOS device, please read 

### ISSUE THREAD

**Issue by sc1884** [AirtestProject/iOS-Tagent#112]
Remove any following parts if does not have details about

**Describe the bug**
A clear and concise description of what the bug is. Or paste traceback below.

```
Hi, I am trying to run a simple connect in IOS App Conection using aiphone xr but seeing the following error:
None
Failed to connect iOS device, please read [Docs]

But i had already passed 1 and 2 step in the doc (http://airtest.netease.com/docs/en/1_online_help/Connecting_iOS.html).All seems work,
and i can see  iPhone screen on the browser(http://127.0.0.1:8100/inspector .)

```
*Smartphone (please complete the following information):**
 - Device: iphone xr
 - OS: IOS 13.1
 - Xcode: 11.0
 -MacOS: mojave 10.14.6

**Comment by luoyuediwu** [comment]
同样错误，iOS12.4.2，xcode 10.2 (10E125)

**Comment by sc1884** [comment]
> Xcode 11 is not supported yet, please try xcode 10.2. Mac can install multiple xcode.

it's work. With Xcode 10.2. Thank you very much
