### ISSUE TITLE
何时能满足12.3.x的ios手机

### ISSUE THREAD

**Issue by StarSkyYe** [AirtestProject/iOS-Tagent#113]
本人环境是macOS 10.15， xcode版本11.1，10.2.1
测试发现，xcode 11.1不被ios-Tagent支持。
xcode10.2.1 虽然被ios-Tagent支持，但是10.2.1版本只能支持到ios系统为12.2版本。

公司使用的ios更多的是12.3的ios版本。

请问这个ios-Tagent什么时候能更新支持更高版本的xcode？

**Comment by EraChen233** [comment]
是的，iOS-Tagent目前最多只能支持到xcode 10.2.1。
更新工作正在排期，还需要一些时间

**Comment by EraChen233** [comment]
iOS-Tagent 已更新，支持最新版xcode 11
