### ISSUE TITLE
请问一下build项目之后，显示的连接地址不是本机地址127.0.0.1，而是一个局域网地址169.254.234.35，端口也是8100

### ISSUE THREAD

**Issue by hhching** [AirtestProject/iOS-Tagent#115]
![image](https://user-images.githubusercontent.com/8326075/67744670-23246100-fa5d-11e9-8537-56546b35731e.png)

虽然也可以连接，但是有点好奇，为啥和文档的不太一样。

**Comment by EraChen233** [comment]
wda启动之后就是一个http服务器哦，我们测试之后发现，这个ip访问不是那么稳定，所以加了一个代理

**Comment by hhching** [comment]
> wda启动之后就是一个http服务器哦，我们测试之后发现，这个ip访问不是那么稳定，所以加了一个代理

很赞，希望可以及时更新一下文档，差点被误导了
