### ISSUE TITLE
在xcode启动IOS-Tagent需要apple开发者账号啊？

### ISSUE THREAD

**Issue by xzhacker123** [AirtestProject/iOS-Tagent#117]
error: There are no accounts registered with Xcode. Add your developer account to Xcode (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')error: No profiles for 'com.netease.WebDriverAgentRunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.netease.WebDriverAgentRunner'. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')

**Comment by EraChen233** [comment]
请仔细阅读Readme 和 Q & A
https://github.com/AirtestProject/iOS-Tagent/blob/master/Introduction/question_zh.md
