### ISSUE TITLE
Poco辅助窗-iOS-UI渲染树无效！

### ISSUE THREAD

**Issue by xin7c** [AirtestProject/iOS-Tagent#12]
App是iPhone的计算器。
切换到stop又切回来，一直无法解析！
<img width="369" alt="image" src="https://user-images.githubusercontent.com/11660641/48047973-be7d5000-e1d4-11e8-98e7-7c6458587fe9.png">

**Comment by brantxiong** [comment]
iPhone截图操作都是正常的么？

**Comment by xin7c** [comment]
> iPhone截图操作都是正常的么？

右侧能看到屏幕，实时的，但是有卡顿的情况在。

点击元素可以跳转，但是无法查看渲染树。

**Comment by brantxiong** [comment]
点击下poco inspector按钮试试

![image](https://user-images.githubusercontent.com/3325773/48176847-01faca00-e34d-11e8-9532-9038141e3ccb.png)

如果还是不行，麻烦贴下Xcode Log窗口的日志。

**Comment by xin7c** [comment]
2018-11-08 14:14:23.008947+0800 WebDriverAgentRunner-Runner[4598:2912666] Running tests...
Test Suite 'All tests' started at 2018-11-08 14:14:24.242
Test Suite 'WebDriverAgentRunner.xctest' started at 2018-11-08 14:14:24.244
Test Suite 'UITestingUITests' started at 2018-11-08 14:14:24.245
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2018-11-08 14:14:24.248
    t =     0.00s Set Up
2018-11-08 14:14:24.265867+0800 WebDriverAgentRunner-Runner[4598:2912666] Built at Nov  6 2018 14:09:23
2018-11-08 14:14:24.321849+0800 WebDriverAgentRunner-Runner[4598:2912666] ServerURLHere->http://10.0.8.64:8100<-ServerURLHere
error in connection_block_invoke_2: Connection interrupted
    t =    96.20s Find the Application 'com.apple.Preferences'
    t =    96.21s     Snapshot accessibility hierarchy for app with pid 4607
    t =    96.93s Find the Application 'com.apple.Preferences'
    t =    96.93s     Snapshot accessibility hierarchy for app with pid 4607
    t =    97.96s Find the Application 'com.apple.Preferences'
    t =    97.96s     Snapshot accessibility hierarchy for app with pid 4607
    t =    98.28s Snapshot accessibility hierarchy for app with pid 4607
    t =    98.35s Find the Application 'com.apple.Preferences'
    t =    98.35s     Snapshot accessibility hierarchy for app with pid 4607
    t =    98.82s Find the Application 'com.apple.Preferences'
    t =    98.82s     Snapshot accessibility hierarchy for app with pid 4607
    t =    99.30s Find the Application 'com.apple.Preferences'
    t =    99.30s     Snapshot accessibility hierarchy for app with pid 4607
    t =    99.78s Find the Application 'com.apple.Preferences'
    t =    99.79s     Snapshot accessibility hierarchy for app with pid 4607
    t =   100.26s Find the Application 'com.apple.Preferences'
    t =   100.26s     Snapshot accessibility hierarchy for app with pid 4607
    t =   100.74s Find the Application 'com.apple.Preferences'
    t =   100.74s     Snapshot accessibility hierarchy for app with pid 4607
    t =   101.22s Find the Application 'com.apple.Preferences'
    t =   101.22s     Snapshot accessibility hierarchy for app with pid 4607
    t =   101.70s Find the Application 'com.apple.Preferences'
    t =   101.70s     Snapshot accessibility hierarchy for app with pid 4607
    t =   102.18s Find the Application 'com.apple.Preferences'
    t =   102.18s     Snapshot accessibility hierarchy for app with pid 4607
    t =   102.66s Find the Application 'com.apple.Preferences'
    t =   102.66s     Snapshot accessibility hierarchy for app with pid 4607
    t =   103.15s Find the Application 'com.apple.Preferences'
    t =   103.15s     Snapshot accessibility hierarchy for app with pid 4607
    t =   104.66s Find the Application 'com.apple.Preferences'
    t =   104.66s     Snapshot accessibility hierarchy for app with pid 4607
    t =   105.12s Find the Application 'com.apple.Preferences'
    t =   105.12s     Snapshot accessibility hierarchy for app with pid 4607
    t =   105.44s Snapshot accessibility hierarchy for app with pid 4607
    t =   105.47s Find the Application 'com.apple.Preferences'
    t =   105.47s     Snapshot accessibility hierarchy for app with pid 4607
    t =   105.97s Find the Application 'com.apple.Preferences'
    t =   105.97s     Snapshot accessibility hierarchy for app with pid 4607
    t =   106.42s Find the Application 'com.apple.Preferences'
    t =   106.42s     Snapshot accessibility hierarchy for app with pid 4607
    t =   106.74s Snapshot accessibility hierarchy for app with pid 4607
    t =   106.78s Find the Application 'com.apple.Preferences'
    t =   106.78s     Snapshot accessibility hierarchy for app with pid 4607
    t =   107.09s Snapshot accessibility hierarchy for app with pid 4607
    t =   107.12s Snapshot accessibility hierarchy for app with pid 4607
2018-11-08 14:16:11.736879+0800 WebDriverAgentRunner-Runner[4598:2912666] Enqueue Failure: Hit testing Application, pid: 4607, label: '设置' at point {207, 368} returned Button, {{0.0, 357.0}, {414.0, 45.0}}, label: '蓝牙', value: 打开 which belongs to Application 'com.apple.Preferences' but is not correctly modeled in its AX hierarchy. Element path:
Application, pid: 4607, label: '设置'








                  Button, {{0.0, 357.0}, {414.0, 45.0}}, label: '蓝牙', value: 打开
Inconsistent relationships:
	Button, {{0.0, 357.0}, {414.0, 45.0}}, label: '蓝牙', value: 打开 claims parent  but is not included in that element's children array. /Users/wuling/workspace/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =   107.60s Snapshot accessibility hierarchy for app with pid 4607
2018-11-08 14:16:12.166311+0800 WebDriverAgentRunner-Runner[4598:2912666] Enqueue Failure: Hit testing NavigationBar, {{0.0, 20.0}, {414.0, 96.0}}, identifier: '设置' at point {207, 68} returned Other, {{0.0, 64.0}, {414.0, 52.0}} which belongs to Application 'com.apple.Preferences' but is not correctly modeled in its AX hierarchy. Element path:
Application, pid: 4607, label: '设置'
  Window, {{0.0, 0.0}, {414.0, 736.0}}
    Other, {{0.0, 0.0}, {414.0, 736.0}}
      Other, {{0.0, 0.0}, {414.0, 736.0}}
        NavigationBar, {{0.0, 20.0}, {414.0, 96.0}}, identifier: '设置'
          Other, {{0.0, 64.0}, {414.0, 52.0}}
Inconsistent relationships:
	Other, {{0.0, 64.0}, {414.0, 52.0}} claims parent NavigationBar, {{0.0, 20.0}, {414.0, 96.0}}, identifier: '设置' but is not included in that element's children array. /Users/wuling/workspace/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =   108.46s Snapshot accessibility hierarchy for app with pid 4607
2018-11-08 14:16:13.030244+0800 WebDriverAgentRunner-Runner[4598:2912666] Enqueue Failure: Hit testing Cell, {{0.0, 151.0}, {414.0, 81.0}}, label: '许楚', value: Apple ID、iCloud、iT... at point {207, 191.5} returned Button, {{0.0, 151.0}, {414.0, 81.0}}, label: '许楚', value: Apple ID、iCloud、iT... which belongs to Application 'com.apple.Preferences' but is not correctly modeled in its AX hierarchy. Element path:
Application, pid: 4607, label: '设置'
  Window, {{0.0, 0.0}, {414.0, 736.0}}
    Other, {{0.0, 0.0}, {414.0, 736.0}}
      Other, {{0.0, 0.0}, {414.0, 736.0}}
        Other, {{0.0, 0.0}, {414.0, 736.0}}
          Other, {{0.0, 0.0}, {414.0, 736.0}}
            Other, {{0.0, 0.0}, {414.0, 736.0}}
              Table, {{0.0, 0.0}, {414.0, 736.0}}
                Cell, {{0.0, 151.0}, {414.0, 81.0}}, label: '许楚', value: Apple ID、iCloud、iT...
                  Button, {{0.0, 151.0}, {414.0, 81.0}}, label: '许楚', value: Apple ID、iCloud、iT...
Inconsistent relationships:
	Button, {{0.0, 151.0}, {414.0, 81.0}}, label: '许楚', value: Apple ID、iCloud、iT... claims parent Cell, {{0.0, 151.0}, {414.0, 81.0}}, label: '许楚', value: Apple ID、iCloud、iT... but is not included in that element's children array. /Users/wuling/workspace/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =   109.00s Snapshot accessibility hierarchy for app with pid 4607
2018-11-08 14:16:13.566112+0800 WebDriverAgentRunner-Runner[4598:2912666] Enqueue Failure: Hit testing Cell, {{0.0, 267.0}, {414.0, 45.0}}, label: '飞行模式', value: 0 at point {207, 289.5} returned StaticText, {{0.0, 267.0}, {414.0, 45.0}}, label: '飞行模式', value: 0 which belongs to Application 'com.apple.Preferences' but is not correctly modeled in its AX hierarchy. Element path:
Application, pid: 4607, label: '设置'
  Window, {{0.0, 0.0}, {414.0, 736.0}}
    Other, {{0.0, 0.0}, {414.0, 736.0}}
      Other, {{0.0, 0.0}, {414.0, 736.0}}
        Other, {{0.0, 0.0}, {414.0, 736.0}}
          Other, {{0.0, 0.0}, {414.0, 736.0}}
            Other, {{0.0, 0.0}, {414.0, 736.0}}
              Table, {{0.0, 0.0}, {414.0, 736.0}}
                Cell, {{0.0, 267.0}, {414.0, 45.0}}, label: '飞行模式', value: 0
                  StaticText, {{0.0, 267.0}, {414.0, 45.0}}, label: '飞行模式', value: 0
Inconsistent relationships:
	StaticText, {{0.0, 267.0}, {414.0, 45.0}}, label: '飞行模式', value: 0 claims parent Cell, {{0.0, 267.0}, {414.0, 45.0}}, label: '飞行模式', value: 0 but is not included in that element's children array. /Users/wuling/workspace/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =   109.37s Snapshot accessibility hierarchy for app with pid 4607
2018-11-08 14:16:13.956658+0800 WebDriverAgentRunner-Runner[4598:2912666] Enqueue Failure: Hit testing Switch, {{343.0, 274.0}, {51.0, 31.0}}, label: '飞行模式', value: 0 at point {368.5, 289.5} returned Other, {{343.0, 274.0}, {51.0, 31.0}} which belongs to Application 'com.apple.Preferences' but is not correctly modeled in its AX hierarchy. Element path:
Application, pid: 4607, label: '设置'
  Window, {{0.0, 0.0}, {414.0, 736.0}}
    Other, {{0.0, 0.0}, {414.0, 736.0}}
      Other, {{0.0, 0.0}, {414.0, 736.0}}
        Other, {{0.0, 0.0}, {414.0, 736.0}}
          Other, {{0.0, 0.0}, {414.0, 736.0}}
            Other, {{0.0, 0.0}, {414.0, 736.0}}
              Table, {{0.0, 0.0}, {414.0, 736.0}}
                Cell, {{0.0, 267.0}, {414.0, 45.0}}, label: '飞行模式', value: 0
                  Switch, {{343.0, 274.0}, {51.0, 31.0}}, label: '飞行模式', value: 0
                    Other, {{343.0, 274.0}, {51.0, 31.0}}
                      Other, {{343.0, 274.0}, {51.0, 31.0}}
Inconsistent relationships:
	Other, {{343.0, 274.0}, {51.0, 31.0}} claims parent Switch, {{343.0, 274.0}, {51.0, 31.0}}, label: '飞行模式', value: 0 but is not included in that element's children array. /Users/wuling/workspace/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =   110.02s Snapshot accessibility hierarchy for app with pid 4607
2018-11-08 14:16:14.589646+0800 WebDriverAgentRunner-Runner[4598:2912666] Enqueue Failure: Hit testing Cell, {{0.0, 312.0}, {414.0, 45.0}}, label: '无线局域网', value: Ling-5G at point {207, 334.5} returned Button, {{0.0, 312.0}, {414.0, 45.0}}, label: '无线局域网', value: Ling-5G which belongs to Application 'com.apple.Preferences' but is not correctly modeled in its AX hierarchy. Element path:
Application, pid: 4607, label: '设置'
  Window, {{0.0, 0.0}, {414.0, 736.0}}
    Other, {{0.0, 0.0}, {414.0, 736.0}}
      Other, {{0.0, 0.0}, {414.0, 736.0}}
        Other, {{0.0, 0.0}, {414.0, 736.0}}
          Other, {{0.0, 0.0}, {414.0, 736.0}}
            Other, {{0.0, 0.0}, {414.0, 736.0}}
              Table, {{0.0, 0.0}, {414.0, 736.0}}
                Cell, {{0.0, 312.0}, {414.0, 45.0}}, label: '无线局域网', value: Ling-5G
                  Button, {{0.0, 312.0}, {414.0, 45.0}}, label: '无线局域网', value: Ling-5G
Inconsistent relationships:
	Button, {{0.0, 312.0}, {414.0, 45.0}}, label: '无线局域网', value: Ling-5G claims parent Cell, {{0.0, 312.0}, {414.0, 45.0}}, label: '无线局域网', value: Ling-5G but is not included in that element's children array. /Users/wuling/workspace/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =   110.72s Snapshot accessibility hierarchy for app with pid 4607
2018-11-08 14:16:15.284515+0800 WebDriverAgentRunner-Runner[4598:2912666] Enqueue Failure: Hit testing Cell, {{0.0, 402.0}, {414.0, 45.0}}, label: '蜂窝移动网络' at point {207, 424.5} returned Button, {{0.0, 402.0}, {414.0, 45.0}}, label: '蜂窝移动网络' which belongs to Application 'com.apple.Preferences' but is not correctly modeled in its AX hierarchy. Element path:
Application, pid: 4607, label: '设置'
  Window, {{0.0, 0.0}, {414.0, 736.0}}
    Other, {{0.0, 0.0}, {414.0, 736.0}}
      Other, {{0.0, 0.0}, {414.0, 736.0}}
        Other, {{0.0, 0.0}, {414.0, 736.0}}
          Other, {{0.0, 0.0}, {414.0, 736.0}}
            Other, {{0.0, 0.0}, {414.0, 736.0}}
              Table, {{0.0, 0.0}, {414.0, 736.0}}
                Cell, {{0.0, 402.0}, {414.0, 45.0}}, label: '蜂窝移动网络'
                  Button, {{0.0, 402.0}, {414.0, 45.0}}, label: '蜂窝移动网络'
Inconsistent relationships:
	Button, {{0.0, 402.0}, {414.0, 45.0}}, label: '蜂窝移动网络' claims parent Cell, {{0.0, 402.0}, {414.0, 45.0}}, label: '蜂窝移动网络' but is not included in that element's children array. /Users/wuling/workspace/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =   111.20s Snapshot accessibility hierarchy for app with pid 4607
2018-11-08 14:16:15.763530+0800 WebDriverAgentRunner-Runner[4598:2912666] Enqueue Failure: Hit testing Cell, {{0.0, 447.0}, {414.0, 45.0}}, label: '个人热点' at point {207, 469.5} returned Button, {{0.0, 447.0}, {414.0, 45.0}}, label: '个人热点' which belongs to Application 'com.apple.Preferences' but is not correctly modeled in its AX hierarchy. Element path:
Application, pid: 4607, label: '设置'
  Window, {{0.0, 0.0}, {414.0, 736.0}}
    Other, {{0.0, 0.0}, {414.0, 736.0}}
      Other, {{0.0, 0.0}, {414.0, 736.0}}
        Other, {{0.0, 0.0}, {414.0, 736.0}}
          Other, {{0.0, 0.0}, {414.0, 736.0}}
            Other, {{0.0, 0.0}, {414.0, 736.0}}
              Table, {{0.0, 0.0}, {414.0, 736.0}}
                Cell, {{0.0, 447.0}, {414.0, 45.0}}, label: '个人热点'
                  Button, {{0.0, 447.0}, {414.0, 45.0}}, label: '个人热点'
Inconsistent relationships:
	Button, {{0.0, 447.0}, {414.0, 45.0}}, label: '个人热点' claims parent Cell, {{0.0, 447.0}, {414.0, 45.0}}, label: '个人热点' but is not included in that element's children array. /Users/wuling/workspace/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =   111.68s Snapshot accessibility hierarchy for app with pid 4607
2018-11-08 14:16:16.250988+0800 WebDriverAgentRunner-Runner[4598:2912666] Enqueue Failure: Hit testing Cell, {{0.0, 492.0}, {414.0, 45.0}}, label: 'VPN', value: 需要更新 at point {207, 514.5} returned Button, {{0.0, 492.0}, {414.0, 45.0}}, label: 'VPN', value: 需要更新 which belongs to Application 'com.apple.Preferences' but is not correctly modeled in its AX hierarchy. Element path:
Application, pid: 4607, label: '设置'
  Window, {{0.0, 0.0}, {414.0, 736.0}}
    Other, {{0.0, 0.0}, {414.0, 736.0}}
      Other, {{0.0, 0.0}, {414.0, 736.0}}
        Other, {{0.0, 0.0}, {414.0, 736.0}}
          Other, {{0.0, 0.0}, {414.0, 736.0}}
            Other, {{0.0, 0.0}, {414.0, 736.0}}
              Table, {{0.0, 0.0}, {414.0, 736.0}}
                Cell, {{0.0, 492.0}, {414.0, 45.0}}, label: 'VPN', value: 需要更新
                  Button, {{0.0, 492.0}, {414.0, 45.0}}, label: 'VPN', value: 需要更新
Inconsistent relationships:
	Button, {{0.0, 492.0}, {414.0, 45.0}}, label: 'VPN', value: 需要更新 claims parent Cell, {{0.0, 492.0}, {414.0, 45.0}}, label: 'VPN', value: 需要更新 but is not included in that element's children array. /Users/wuling/workspace/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =   112.20s Snapshot accessibility hierarchy for app with pid 4607
2018-11-08 14:16:16.799961+0800 WebDriverAgentRunner-Runner[4598:2912666] Enqueue Failure: Hit testing Cell, {{0.0, 572.0}, {414.0, 45.0}}, label: '通知' at point {207, 594.5} returned (null) which is from the same process but cannot be mapped using AX data: Error getting main window kAXErrorServerNotFound /Users/wuling/workspace/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
2018-11-08 14:16:29.055368+0800 WebDriverAgentRunner-Runner[4598:2912666] Failed to resolve hit point for Cell, 0x2808570c0, {{0.0, 572.0}, {414.0, 45.0}}, label: '通知' -

**Comment by xin7c** [comment]
完全没反应，而且操作iphone，iOS Screen卡顿太厉害了，完全不会切换。
1.0.1我记得是OK的啊。

**Comment by brantxiong** [comment]
能给下你的iOS, Xcode, Mac环境版本么？

**Comment by xin7c** [comment]
手机：iPhone 6s Plus
系统版本：12.0.1
Mac如图：
![image](https://user-images.githubusercontent.com/11660641/48183048-6bd49d00-e368-11e8-8f88-229746e81cdb.png)

**Comment by brantxiong** [comment]
用的是我们的iOS-tagent么？https://github.com/AirtestProject/iOS-Tagent 
打开 http://127.0.0.1:8100/source?format=json 这个看看有没有数据。

**Comment by brantxiong** [comment]
要在AirtestIDE里显示Poco树，需要使用我们修改过的 iOS-Targent。https://github.com/AirtestProject/iOS-Tagent

**Comment by xin7c** [comment]
> 要在AirtestIDE里显示Poco树，需要使用我们修改过的 iOS-Targent。https://github.com/AirtestProject/iOS-Tagent

可是之前我从未用过你们修改过的targent，一样生效过，只是最近不行了。

**Comment by brantxiong** [comment]
嗯，操作一样的，我们做了优化和适配Poco

**Comment by xin7c** [comment]
> 嗯，操作一样的，我们做了优化和适配Poco

good，修改了bundle id，现在可以了   感谢  

![image](https://user-images.githubusercontent.com/11660641/48187294-9f69f400-e375-11e8-976d-743def2d0b37.png)


但是安卓的问题还请排查，谢谢！

**Comment by brantxiong** [comment]
好的，这个issue先关闭了哈

**Comment by zuiqingfengyang** [comment]
新版IDE就兼容了appium 着实好用
