### ISSUE TITLE
iOS Screen 被放大

### ISSUE THREAD

**Issue by zhuruiqi** [AirtestProject/iOS-Tagent#120]
Xcode 版本：10.3
测试机：iphone6p，iOS 10.3.2
python 2.7.10
AirtestIDE：1.2.2
如图，屏幕被放大了。请问如何解决？
![image](https://user-images.githubusercontent.com/26532614/68852051-13ba3e80-0712-11ea-9152-700c91304486.png)

**Comment by EraChen233** [comment]
再装一个 xcode 10.1，或者等我们下一个版本iOS-Tagent更新

**Comment by EraChen233** [comment]
iOS-Tagent已更新
