### ISSUE TITLE
IDE运行脚本，安卓device screen会被断开

### ISSUE THREAD

**Issue by xin7c** [AirtestProject/iOS-Tagent#13]
如题，请问这样是正确的吗？？

**Comment by brantxiong** [comment]
应该不会，你是在同一台设备上运行脚本么？

**Comment by xin7c** [comment]
是的，同一台 我记得上一根本的IDE还不会这样，更新之后就这样了，很奇怪啊。

**Comment by yimelia** [comment]
本地是否有安装ADB？看看把本地环境的ADB版本更新到40看看，新版本的ADB升级到了40

**Comment by xin7c** [comment]
刚刚确认了，这个问题在IDE v1.0.0上是不存在的。

**Comment by xin7c** [comment]
> 本地是否有安装ADB？看看把本地环境的ADB版本更新到40看看，新版本的ADB升级到了40

Android Debug Bridge version 1.0.40
Version 4797878
Installed as /usr/local/bin/adb

这个是啥版本？我觉得不应该啊。

**Comment by xin7c** [comment]
> 感谢反馈。

可是1.1.0有问题啊····

有什么解决办法嘛？

**Comment by rockywhisper** [comment]
@xin7c  你好，请问你是用的Mac版IDE，还是Windows版本？

**Comment by rockywhisper** [comment]
@xin7c  

你好，这个属于IDE的使用问题，我先把这个issues关掉啦。
可以到[IDE仓库的issues内](https://github.com/AirtestProject/AirtestIDE/issues)新建一个。
