### ISSUE TITLE
Command CodeSign failed with a nonzero exit code

### ISSUE THREAD

**Issue by arronhai** [AirtestProject/iOS-Tagent#136]
![8A4B5C0C-2580-47B6-9392-0FE961887DCB](https://user-images.githubusercontent.com/42204523/71611827-24961500-2bd7-11ea-9984-e556cb514b8a.png)
Please follow the picture above, I set the right signing identifier, but it always comes to "Command CodeSign failed with a nonzero exit code"

**Comment by EraChen233** [comment]
https://stackoverflow.com/questions/52421999/xcode-10-command-codesign-failed-with-a-nonzero-exit-code
