### ISSUE TITLE
IOS截图点击的位置与实际模拟点击的位置有误差

### ISSUE THREAD

**Issue by Sammsuo** [AirtestProject/iOS-Tagent#137]
ios13.3
Xcode11.3
macOS 10.15.2

在使用touch截图出来后，发现与实际点击的位置有相当大的误差
![image](https://user-images.githubusercontent.com/37886008/71659922-4680ca80-2d84-11ea-9414-10710a5ae27c.png)
滑动的是左下方，笔画出现在右上方

**Comment by EraChen233** [comment]
已发现是bug，可参考这个回复
https://github.com/AirtestProject/AirtestIDE/issues/676#issuecomment-571400529

**Comment by Sammsuo** [comment]
谢谢~~
