### ISSUE TITLE
iOS13.3.1 上无法启动

### ISSUE THREAD

**Issue by shishangx** [AirtestProject/iOS-Tagent#142]
手机：iphone 8 ｜ iOS13.3.1

问题描述：
mac上编译成功后，执行test，log中错误信息：
`WebDriverAgentRunner-Runner.app (347) encountered an error (Failed to load the test bundle. (Underlying error: 未能载入软件包“WebDriverAgentRunner”，因为它已损坏或丢失必要的资源。. 软件包已损坏或丢失必要的资源。. dlopen_preflight(/var/containers/Bundle/Application/98E47DEF-313C-4ABD-8E4B-BF72530A917D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): no suitable image found.  Did find:
	/var/containers/Bundle/Application/98E47DEF-313C-4ABD-8E4B-BF72530A917D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: code signature invalid for '/var/containers/Bundle/Application/98E47DEF-313C-4ABD-8E4B-BF72530A917D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner'`

不知道有什么好的建议？

**Comment by EraChen233** [comment]
报错信息提示 code signature invalid ，注意看教程
https://github.com/AirtestProject/iOS-Tagent/blob/master/Introduction/question_zh.md#%E7%99%BB%E9%99%86%E5%BC%80%E5%8F%91%E8%80%85%E8%B4%A6%E5%8F%B7

**Comment by CrazyTianC** [comment]
尝试13.3

**Comment by q88535448** [comment]
相同的配置在13.3.1之前的版本是可以的，只有13.3.1不行，麻烦看看吧

**Comment by q88535448** [comment]
> 尝试13.3

xcode 13.3吗 你试过了吗

**Comment by zhanglianps** [comment]
您好，请问这个问题你解决了吗？我也遇到了相同的情况

**Comment by zhanglianps** [comment]
> 手机：iphone 8 ｜ iOS13.3.1
> 
> 问题描述：
> mac上编译成功后，执行test，log中错误信息：
> `WebDriverAgentRunner-Runner.app (347) encountered an error (Failed to load the test bundle. (Underlying error: 未能载入软件包“WebDriverAgentRunner”，因为它已损坏或丢失必要的资源。. 软件包已损坏或丢失必要的资源。. dlopen_preflight(/var/containers/Bundle/Application/98E47DEF-313C-4ABD-8E4B-BF72530A917D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): no suitable image found. Did find: /var/containers/Bundle/Application/98E47DEF-313C-4ABD-8E4B-BF72530A917D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: code signature invalid for '/var/containers/Bundle/Application/98E47DEF-313C-4ABD-8E4B-BF72530A917D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner'`
> 
> 不知道有什么好的建议？

您好，请问这个问题你解决了吗？我也遇到了相同的情况

**Comment by zhanglianps** [comment]
您好，请问这个问题你解决了吗？我也遇到了相同的情况

**Comment by tobyatuipath** [comment]
Xcode 10.1 + iOS 13.3.1 试了可行

**Comment by tobyatgithub** [comment]
Xcode 10.1 + iOS 13.3.1 试了可行

**Comment by 1Windy** [comment]
Xcode 11.6 + IOS 13.3.1 同样报错
Xcode 11.6 + IOS 12.4.8 可以运行
猜测 IOS 13.3.1版本不支持？

**Comment by Teng** [comment]
> Xcode 10.1 + iOS 13.3.1 试了可行

跪求如何搞定低版本xcode下使用高版本iOS的问题,我也是13.3.1.  用xcode10.1安装网上的复制文件到 DeviceSupport 目录的方法,会提示未知错误
