### ISSUE TITLE
在iOS真机连接后，，在真机界面是连接成功的，但是一旦打开某个app，就如下图这个状态,会闪退出去

### ISSUE THREAD

**Issue by CCyya** [AirtestProject/iOS-Tagent#15]
![2018-11-20 3 46 43](https://user-images.githubusercontent.com/43335165/48758922-8ef23b80-ecdc-11e8-8c99-14aabbe81ed9.png)
![2018-11-20 3 47 19](https://user-images.githubusercontent.com/43335165/48758924-90bbff00-ecdc-11e8-9a4b-576983023a69.png)
![2018-11-20 3 53 42](https://user-images.githubusercontent.com/43335165/48758928-91549580-ecdc-11e8-94e3-2344bd10b35b.png)
![2018-11-20 3 53 55](https://user-images.githubusercontent.com/43335165/48758930-91ed2c00-ecdc-11e8-9a68-6d51bcd1ee6c.png)

**Comment by CCyya** [comment]
mac 10.12.6, iphone 6sp

**Comment by brantxiong** [comment]
iPhone系统版本是多少？

**Comment by EraChen233** [comment]
这个issue长期没有更新，我先暂时关闭了，如果有更多信息的反馈（请重新打开这个issue）
