### ISSUE TITLE
使用tpl模板template.match_in时设置了rbg=True,用有颜色的图去匹配,会匹配到灰色图

### ISSUE THREAD

**Issue by xuezh01** [AirtestProject/iOS-Tagent#155]
使用tpl模板template.match_in时设置了rbg=True,用有颜色的图去匹配,会匹配到灰色图

ST.CVSTRATEGY = ["tpl"]

def test(template):
    screen = G.DEVICE.snapshot()
    template.rgb = True
    focus_pos = template.match_in(screen )

![image](https://user-images.githubusercontent.com/24462070/78136843-dce18c80-7456-11ea-9ec6-495d55f90145.png)

**Comment by yimelia** [comment]
尽量选择一些特征点更加明显的内容来截图，只是勾选rgb的话，有时候它仍然认为这个结果是最佳匹配。因为图像匹配不是100%准确，只能匹配出一个可信度，只要超过了你设置的阈值就会认为成功。
可以参考：https://airtest.doc.io.netease.com/tutorial/9_Improved_compatibility/
