### ISSUE TITLE
airtest连接时，提示NSUnownKeyException错误

### ISSUE THREAD

**Issue by JustForLife** [AirtestProject/iOS-Tagent#157]
环境信息：

XCode： 9.0
IPhone： 6
IOS版本： 9.0.2

问题描述：
1）xCode上运行Test后，WDA在iPhone 6 上安装成功，并且设置了证书信任
2）在浏览器，输入IP:8100/stauts可以看到设备信息
3）在浏览器，输入IP:8100/inspector，报如下错误
2020-04-26 09:06:24.853 WebDriverAgentRunner-Runner[371:72605] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<XCAXClient_iOS 0x15c6239a0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key applicationProcessTracker.'
*** First throw call stack:
(0x182854f5c 0x19744bf80 0x182854c1c 0x183759d90 0x1836ac0cc 0x1024b8628 0x197c45770 0x197c465b4 0x1024b85fc 0x1024c11b4 0x1024bedec 0x1024c0f54 0x1024aeb9c 0x1024a716c 0x1024a1b84 0x106e463cc 0x106e46b80 0x197c45770 0x197c54d84 0x197c45770 0x197c4ae20 0x18280c258 0x18280a0c0 0x182738dc0 0x1836ac7ec 0x1024a10c0 0x102487be4 0x18285aa80 0x1827585f4 0x1001140a8 0x100113e58 0x100159780 0x100113ba0 0x100114c78 0x10015e778 0x100114674 0x100110868 0x100110290 0x1001104a0 0x100110868 0x100110290 0x1001104a0 0x100110868 0x100110290 0x1001104a0 0x100167f5c 0x1001233e8 0x100167dd8 0x1000ffed0 0x10015d920 0x18280c48c 0x18280bdc4 0x182809d28 0x182738dc0 0x18d88c088 0x187e12f44 0x1000b8430 0x197c768b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

4）使用AirIDE，连接 IP:8100连接设备，提示如下错误
2020-04-26 09:06:24.853 WebDriverAgentRunner-Runner[371:72605] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<XCAXClient_iOS 0x15c6239a0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key applicationProcessTracker.'
*** First throw call stack:
(0x182854f5c 0x19744bf80 0x182854c1c 0x183759d90 0x1836ac0cc 0x1024b8628 0x197c45770 0x197c465b4 0x1024b85fc 0x1024c11b4 0x1024bedec 0x1024c0f54 0x1024aeb9c 0x1024a716c 0x1024a1b84 0x106e463cc 0x106e46b80 0x197c45770 0x197c54d84 0x197c45770 0x197c4ae20 0x18280c258 0x18280a0c0 0x182738dc0 0x1836ac7ec 0x1024a10c0 0x102487be4 0x18285aa80 0x1827585f4 0x1001140a8 0x100113e58 0x100159780 0x100113ba0 0x100114c78 0x10015e778 0x100114674 0x100110868 0x100110290 0x1001104a0 0x100110868 0x100110290 0x1001104a0 0x100110868 0x100110290 0x1001104a0 0x100167f5c 0x1001233e8 0x100167dd8 0x1000ffed0 0x10015d920 0x18280c48c 0x18280bdc4 0x182809d28 0x182738dc0 0x18d88c088 0x187e12f44 0x1000b8430 0x197c768b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Howarden34** [comment]
你是不是拒绝过xcode的密码权限请求了呀？
