### ISSUE TITLE
Version 11.4.1 (11E503a)  ios13.4 iphone6s 

### ISSUE THREAD

**Issue by chenliucai** [AirtestProject/iOS-Tagent#158]
2020-05-12 16:50:46.011053+0800 WebDriverAgentRunner-Runner[1274:110553] -[UITestingUITests internalImplementation]: unrecognized selector sent to instance 0x282d64b40
    t =     0.02s     Assertion Failure: <unknown>:0: failed: caught "NSInvalidArgumentException", "-[UITestingUITests internalImplementation]: unrecognized selector sent to instance 0x282d64b40"
(
	0   CoreFoundation                      0x00000001b201c604 409609CD-8410-38E1-BA5D-BDED609D2018 + 1222148
	1   libobjc.A.dylib                     0x00000001b1d3ebcc objc_exception_throw + 56
	2   CoreFoundation                      0x00000001b1f20ea8 409609CD-8410-38E1-BA5D-BDED609D2018 + 192168
	3   CoreFoundation                      0x00000001b2020694 409609CD-8410-38E1-BA5D-BDED609D2018 + 1238676
	4   CoreFoundation                      0x00000001b20225bc _CF_forwarding_prep_0 + 92
	5   WebDriverAgentLib                   0x0000000108731378 -[FBFailureProofTestCase setUp] + 96
	6   XCTest                              0x0000000104712c88 __48-[XCTestCase _performSetUpSequenceWithSelector:]_block_invoke_2 + 492
	7   XCTest                              0x00000001047680d8 +[XCTestCase(Failures) performFailableBlock:testCase:testCaseRun:shouldInterruptTest:] + 84
	8   XCTest                              0x0000000104767fdc -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 132
	9   XCTest                              0x0000000104712a7c __48-[XCTestCase _performSetUpSequenceWithSelector:]_block_invoke + 116
	10  XCTest                              0x0000000104779d7c -[XCTContext _runActivityNamed:type:block:] + 248
	11  XCTest                              0x000000010471b480 -[XCTestCase startActivityWithTitle:type:block:] + 200
	12  XCTest                              0x000000010471b630 -[XCTestCase startActivityWithTitle:block:] + 72
	13  XCTest                              0x00000001047129f8 -[XCTestCase _performSetUpSequenceWithSelector:] + 108
	14  XCTest                              0x0000000104710d68 -[XCTestCase invokeTest] + 728
	15  XCTest                              0x00000001047128b8 __26-[XCTestCase performTest:]_block_invoke_2 + 44
	16  XCTest                              0x00000001047680d8 +[XCTestCase(Failures) performFailableBlock:testCase:testCaseRun:shouldInterruptTest:] + 84
	17  XCTest                              0x0000000104767fdc -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 132
	18  XCTest                              0x00000001047127f0 __26-[XCTestCase performTest:]_block_invoke.366 + 96
	19  XCTest                              0x000000010477a48c +[XCTContext runInContextForTestCase:block:] + 212
	20  XCTest                              0x00000001047120dc -[XCTestCase performTest:] + 540
	21  XCTest                              0x000000010475586c -[XCTest runTest] + 60
	22  XCTest                              0x000000010470c5c8 __27-[XCTestSuite performTest:]_block_invoke + 268
	23  XCTest                              0x000000010470be58 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
	24  XCTest                              0x000000010477a48c +[XCTContext runInContextForTestCase:block:] + 212
	25  XCTest                              0x000000010470be00 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 156
	26  XCTest

**Comment by Howarden34** [comment]
iOS版本13.4以上的适配已经在测试了，近期会更新出来

**Comment by chenliucai** [comment]
期待 谢谢！
