### ISSUE TITLE
xcode13.3.1，运行后报错Library not loaded: @rpath/YYCache.framework/YYCache

### ISSUE THREAD

**Issue by baiguo** [AirtestProject/iOS-Tagent#167]
2020-07-15 16:22:20.454566+0800 WebDriverAgentRunner-Runner[5085:3400058] Running tests...
2020-07-15 16:22:20.665081+0800 WebDriverAgentRunner-Runner[5085:3400058] 未能载入软件包“WebDriverAgentRunner”，因为它已损坏或丢失必要的资源。 请尝试重新安装软件包。
2020-07-15 16:22:20.665162+0800 WebDriverAgentRunner-Runner[5085:3400058] (dlopen_preflight(/var/containers/Bundle/Application/257BB389-AC3D-4777-B03A-34B1A0BF41EE/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/YYCache.framework/YYCache
  Referenced from: /private/var/containers/Bundle/Application/257BB389-AC3D-4777-B03A-34B1A0BF41EE/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/257BB389-AC3D-4777-B03A-34B1A0BF41EE/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/YYCache.framework/YYCache: code signature invalid for '/private/var/containers/Bundle/Application/257BB389-AC3D-4777-B03A-34B1A0BF41EE/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/YYCache.framework/YYCache'
)

**Comment by baiguo** [comment]
我的是xcode11.3.1 ios 12 和 13 都不行

**Comment by saberloki** [comment]
xcode11.3.1 ios12.4.3 同样有这个报错

**Comment by vivian12** [comment]
我一开始是可以运行成功的，但是后来删了mobiledriver文件下的东西，也就一样犯这个错误，已经折腾三天了，没有解决办法，咋办

**Comment by baiguo** [comment]
> 我一开始是可以运行成功的，但是后来删了mobiledriver文件下的东西，也就一样犯这个错误，已经折腾三天了，没有解决办法，咋办

我是直接下载的就报错， 官方也没有人回复，

**Comment by yajuntang** [comment]
来，热心市民回复一下怎么解决这个问题.
![image](https://gitee.com/tangyajun/Images/raw/master//01.png)
![image](https://gitee.com/tangyajun/Images/raw/master//02.png)
![image](https://gitee.com/tangyajun/Images/raw/master//03.png)
![image](https://gitee.com/tangyajun/Images/raw/master//04.png)
![image](https://gitee.com/tangyajun/Images/raw/master//05.png)
