### ISSUE TITLE
Airtestide连接ios成功，但真机界面显示不出来

### ISSUE THREAD

**Issue by xiayan5** [AirtestProject/iOS-Tagent#17]
Airtestide连接ios成功，但真机界面显示不出来，但是访问http://127.0.0.1:8100/inspector地址，能显示真机的界面，不知道是什么原因？
求指导~谢谢

**Comment by yimelia** [comment]
请问是否根据[文档](http://airtest.netease.com/docs/cn/2_device_connection/4_ios_connection.html) 进行的部署，并且确认部署的项目是ios-Tagent，同时，能够看到文档中成功部署描述的[log内容](http://airtest.netease.com/docs/cn/2_device_connection/4_ios_connection.html#id13)？
真机界面显示不出来是什么样的？是否有报错内容？可以通过[命令行启动IDE](http://airtest.netease.com/docs/cn/9_faq/1_ide_crash.html#id2)的方式来查看到报错log

**Comment by EraChen233** [comment]
这个issue长期没有更新，我先暂时关闭了，如果有更多信息的反馈（请重新打开这个issue）
