### ISSUE TITLE
部署时设置依赖库为webdriveragent然后部署会报错，请问是我部署的姿势不对么

### ISSUE THREAD

**Issue by maxsteamedbread** [AirtestProject/iOS-Tagent#18]
LSadmin10091deMacBook-Pro:ios-tagent lsadmin10091$ touch Cartfile
LSadmin10091deMacBook-Pro:ios-tagent lsadmin10091$ open -a Xcode Cartfile
LSadmin10091deMacBook-Pro:ios-tagent lsadmin10091$ carthage update --platform iOS
*** Fetching WebDriverAgent
*** Fetching RoutingHTTPServer
*** Checking out RoutingHTTPServer at "v1.0.1"
*** Checking out WebDriverAgent at "bbd00099a5fc053748aea8a2c4a1f956154cc7df"
*** xcodebuild output can be found in /var/folders/p3/zpk3gy6n7z5fg344l3p_d2wm0000gn/T/carthage-xcodebuild.Dc9cx2.log
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
*** Building scheme "WebDriverAgentLib" in WebDriverAgent.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/lsadmin10091/Desktop/ios-tagent/Carthage/Checkouts/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentLib -configuration Release -derivedDataPath /Users/lsadmin10091/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/WebDriverAgent/bbd00099a5fc053748aea8a2c4a1f956154cc7df -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/p3/zpk3gy6n7z5fg344l3p_d2wm0000gn/T/WebDriverAgent SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/lsadmin10091/Desktop/ios-tagent/Carthage/Checkouts/WebDriverAgent)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/p3/zpk3gy6n7z5fg344l3p_d2wm0000gn/T/carthage-xcodebuild.Dc9cx2.log

**Comment by MrFuFuFu** [comment]
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
