### ISSUE TITLE
ios9.2设备链接失败，tagent启动正常，iproxy有报错

### ISSUE THREAD

**Issue by fishermanjohn001** [AirtestProject/iOS-Tagent#19]
![reliao_img_1546872725741](https://user-images.githubusercontent.com/38064718/50774636-ea997800-12ce-11e9-8c8f-df62b82a100e.png)
![reliao_img_1546872732824](https://user-images.githubusercontent.com/38064718/50774638-ea997800-12ce-11e9-97d6-65cb98e3f3ea.png)
![reliao_img_1546872738352](https://user-images.githubusercontent.com/38064718/50774639-eb320e80-12ce-11e9-91ff-92cf1d6dc8fc.png)

**Comment by yimelia** [comment]
ios9.2版本过低了，我们手头没有对应的测试机，也没有做对应的兼容性测试和支持，非常抱歉

**Comment by yimelia** [comment]
但是如果只是iproxy的报错的话，可以考虑换个端口号试一下？
