### ISSUE TITLE
mac按照教程部署了iOS-Tagent且AirTest IDE连接成功，但是在windows上不行

### ISSUE THREAD

**Issue by wq1308786830** [AirtestProject/iOS-Tagent#20]
如题，windows10，总报由于远程计算机积极拒绝无法连接的问题

**Comment by wq1308786830** [comment]
还有，mac上一旦Xcode关闭，也连不上ios手机了

**Comment by yimelia** [comment]
是否使用了wdaproxy，还是用的是iproxy？

**Comment by wq1308786830** [comment]
> 是否使用了wdaproxy，还是用的是iproxy？

iproxy，有影响吗，该怎么办啊

**Comment by yimelia** [comment]
看一下文档的 [这里](http://airtest.netease.com/docs/cn/2_device_connection/4_ios_connection.html#id14)，换用wdaproxy就可以进行远程的连接了，连接前请确认两台计算机之间的ip是互通的。

以及xcode关闭项目后，是连不上ios手机的。

**Comment by wq1308786830** [comment]
> 看一下文档的 [这里](http://airtest.netease.com/docs/cn/2_device_connection/4_ios_connection.html#id14)，换用wdaproxy就可以进行远程的连接了，连接前请确认两台计算机之间的ip是互通的。
> 
> 以及xcode关闭项目后，是连不上ios手机的。

不是，我都是usb连接的，windows上不是说可以连接的吗？难道只是能远程连接必须在mac电脑上先通过xcode test连接？

**Comment by yimelia** [comment]
文档里描述得很清楚了。

**Comment by yimelia** [comment]
文档里已经叙述清楚
1. 要连ios手机 **必须** 准备一台mac
2. 需要用xcode将ios-Tagent项目运行起来
3. 跑起来以后可以用iproxy进行端口映射后，连上ios，如果有windows连接需求，需要换用wdaproxy才能进行远程的连接
4. 没有mac，只有windows的话，是无法连接到ios的
![image](https://user-images.githubusercontent.com/6896468/51231396-59956180-199e-11e9-92aa-e316c6d94bfd.png)

![image](https://user-images.githubusercontent.com/6896468/51231401-62863300-199e-11e9-97ca-085f00025b13.png)
