### ISSUE TITLE
AirtestIDE连接iOS无响应；iOS设备上通过浏览器http://127.0.0.1:8100/inspector 可以看到iPhone屏幕，但在AirtestIDE上无法展示

### ISSUE THREAD

**Issue by Ted-ty** [AirtestProject/iOS-Tagent#204]
iOS设备上通过浏览器http://127.0.0.1:8100/inspector 可以看到iPhone屏幕投影，但在AirtestIDE上无法展示
iOS设备：iOS10.1.1
AirtestIDE：v1.2.6

**Comment by Ted-ty** [comment]
长时间等待后，某一次连接后，AirtestIDE上成功展示；但断开连接后再连，AirtestIDE依旧没有投影出iPhone屏幕，难受～～

**Comment by yimelia** [comment]
ios10.1的版本有可能会太低，暂时还不清楚原因，可以考虑换用https://github.com/appium/WebDriverAgent 部署然后再连接试试，用最新版的IDE连（1.2.8）
