### ISSUE TITLE
xcode 12.4 和ios14.4问题

### ISSUE THREAD

**Issue by hunanyy** [AirtestProject/iOS-Tagent#206]

**Comment by hunanyy** [comment]
如下图，中对应对localhost:8100/status后sessionid为null问题，以及对应对localhost:8100/inspector看不到手机元素问题
![image](https://user-images.githubusercontent.com/42541987/109620395-c9fa9f00-7b74-11eb-81cc-9048b8ec4e9a.png)

**Comment by yimelia** [comment]
高版本的xcode和ios版本，可以改为部署appium的https://github.com/appium/WebDriverAgent
