### ISSUE TITLE
xcode12.4 部署不了，详解截图

### ISSUE THREAD

**Issue by wenhuichen** [AirtestProject/iOS-Tagent#207]
<img width="991" alt="xcode12 4" src="https://user-images.githubusercontent.com/6110769/110114492-b7d86500-7def-11eb-9278-e62b55f5d2fa.png">

**Comment by JesseWeb** [comment]
same results to me

**Comment by yimelia** [comment]
可以用 https://github.com/appium/WebDriverAgent 代替 @wenhuichen 


You can use https://github.com/appium/WebDriverAgent instead @JesseWeb
