### ISSUE TITLE
通过浏览器访问8100:/remote不支持远程滑动手机吗？

### ISSUE THREAD

**Issue by Maxdong24** [AirtestProject/iOS-Tagent#21]
ios-tagent运行起来了，airtext也可以，我用浏览器访问8100:/remote对手机进行远程操作，不支持滑动吗？为什么不可以滑动？

**Comment by brantxiong** [comment]
需要通过Airtest IDE进行连接，网页端暂时不支持滑动。

**Comment by Maxdong24** [comment]
> 需要通过Airtest IDE进行连接，网页端暂时不支持滑动。

谢谢~~期望后期能加上呢
