### ISSUE TITLE
ios-agent构建成功，真机连接成功，但是调用API失败，start_app()报错

### ISSUE THREAD

**Issue by wangcodefind** [AirtestProject/iOS-Tagent#22]
agent部署成功，真机链接也成功，poco.click()可以正常运行，但是
调用start_app()失败报错，报错信息如下：

> requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8100): Read timed out. (read timeout=60.0)

看官网上ios支持使用API（start_app），同样的调用方法，在安卓手机上能正常打开APP，ios一直报错
方法如下：
`start_app(package="com.finance.product",activity=None)`
哪位大佬遇到过，求解！

**Comment by brantxiong** [comment]
iOS包的bundle id是对的么？可以试下系统应用启动是否成功：
```python
start_app('com.apple.mobilesafari')
```

**Comment by EraChen233** [comment]
这个issue长期没有更新，我先暂时关闭了，如果有更多信息的反馈（请重新打开这个issue）

**Comment by agoraHan** [comment]
ios 11 启动没问题
ios12.4.1调用start_app()后 APP启动了但是之后抛出异常
E               requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8100): Read timed out. (read timeout=60.0)
