### ISSUE TITLE
WDA在iPhone启动后，Mac无法通过URL连接iPhone

### ISSUE THREAD

**Issue by jiyzhang** [AirtestProject/iOS-Tagent#232]
编译iOS-Tagent并在iPhone上运行，界面一直有
  Automation Running
的白字，应该说WDA已经在iPhone上运行。

Xcode的debug area, 显示如下信息：
`2022-06-29 09:22:34.762370+0800 WebDriverAgentRunner-Runner[4263:174430] ServerURLHere->http://192.168.31.161:8100<-ServerURLHere
2022-06-29 09:22:34.762564+0800 WebDriverAgentRunner-Runner[4263:174665] Using singleton test manager`

但无论是访问
`http://192.168.31.161:8100/status`
还是用iProxy
`iproxy 8100 8100`
都没有反应，界面停在:
`
$ iproxy 8100 8100
Creating listening port 8100 for device port 8100
waiting for connection
`
调试了一晚，没有解决，寻求帮助。

**Comment by jiyzhang** [comment]
发帖后直接连接 127.0.0.1:8100居然就可以了

`
$ curl 127.0.0.1:8100/status
{
  "value" : {
    "build" : {
      "time" : "Apr 12 2022 15:36:09",
      "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
    },
    "os" : {
      "testmanagerdVersion" : 28,
      "name" : "iOS",
      "sdkVersion" : "15.4",
      "version" : "15.5"
    },
    "Version" : "1.1",
    "ios" : {
      "ip" : "192.168.31.161"
    },
    "message" : "WebDriverAgent is ready to accept commands",
    "state" : "success",
    "ready" : true
  },
  "sessionId" : null
}
`

AirtestIDE也连上了，不知道昨晚调试的哪个环节过了

**Comment by biu2016** [comment]
调试了什么内容啊，我也一直卡在Creating listening port 8100 for device port 8100
waiting for connection 上，一直连不上
