### ISSUE TITLE
xcode编译启动成功，设置代理失败，iproxy 8100 8100卡住

### ISSUE THREAD

**Issue by StevenXUzw** [AirtestProject/iOS-Tagent#28]
按教程执行到看到wdaDriverAgent test启动成功，看到日志打印，iproxy时卡在waitting for connection

**Comment by HathawayC** [comment]
> 按教程执行到看到wdaDriverAgent test启动成功，看到日志打印，iproxy时卡在waitting for connection

你这两个地方做了吗
1、设备是否通过数据线连接到电脑，并且信任电脑
2、Airtest IDE是否连接设备

![image](https://user-images.githubusercontent.com/5961185/53614322-8763fc00-3c14-11e9-855b-b32bada5bf39.png)

**Comment by StevenXUzw** [comment]
连接成功的

**Comment by biu2016** [comment]
你解决了这个问题么，我也是一直卡死 wait for connection

**Comment by dyr136006** [comment]
求问这个有解决方案吗
