### ISSUE TITLE
Xcode-beta 10.2 Messaging unqualified id

### ISSUE THREAD

**Issue by SUDARSHANCHAUDHARI** [AirtestProject/iOS-Tagent#33]
I am facing issue about "unqualified id" with WebDriverAgentRunner .
Build is succeed but test is failing

i think it is related to this >> https://github.com/facebook/WebDriverAgent/issues/1089

Kindly check the log

[error.txt](https://github.com/AirtestProject/iOS-Tagent/files/3008198/error.txt)

**Comment by EraChen233** [comment]
Try this. Can it help ?
> Workaround: add the following to the parameters for xcodebuild:
GCC_TREAT_WARNINGS_AS_ERRORS=0

**Comment by SUDARSHANCHAUDHARI** [comment]
@EraChen233 , Can you help me with syntax , where to use this parameter and how?

**Comment by SUDARSHANCHAUDHARI** [comment]
I changed the value of "GCC_TREAT_WARNINGS_AS_ERRORS=0 from GCC_TREAT_WARNINGS_AS_ERRORS=YES" - in file ProjectSettings.xcconfig from Configurations folder

Now I am getting this error, may be same
-----------------------
2019-03-27 12:53:38.252005+0700 WebDriverAgentRunner-Runner[392:30120] +[CATransaction synchronize] called within transaction
2019-03-27 12:53:38.279854+0700 WebDriverAgentRunner-Runner[392:30120] Running tests...
2019-03-27 12:53:38.331208+0700 WebDriverAgentRunner-Runner[392:30120] The bundle “WebDriverAgentRunner” couldn’t be loaded. Try reinstalling the bundle.
2019-03-27 12:53:38.331273+0700 WebDriverAgentRunner-Runner[392:30120] (dlopen(/var/containers/Bundle/Application/2EDAD69B-E921-41C8-BA18-ACCD639D32D6/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner, 265): Symbol not found: _OBJC_CLASS_$_XCEventGenerator
  Referenced from: /private/var/containers/Bundle/Application/2EDAD69B-E921-41C8-BA18-ACCD639D32D6/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Expected in: /private/var/containers/Bundle/Application/2EDAD69B-E921-41C8-BA18-ACCD639D32D6/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest
 in /private/var/containers/Bundle/Application/2EDAD69B-E921-41C8-BA18-ACCD639D32D6/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib)
___________________________________

**Comment by EraChen233** [comment]
xcodebuild  is a command-line tool that allows you to perform build, query, analyze, test, and archive operations on your Xcode projects and workspaces from the command line.

`GCC_TREAT_WARNINGS_AS_ERRORS=0` can be added to the command line like:

![image](https://user-images.githubusercontent.com/5961185/55056215-8782da80-50a0-11e9-9522-041384d56a06.png)

Change the configuration in ProjectSettings.xcconfig may have the same effect.

I have noticed that you mentioned "Xcode-beta 12". What is that means? The latest version of Xcode is 10.2 released in Mar 26, 2019.

**Comment by SUDARSHANCHAUDHARI** [comment]
@EraChen233, I changed the issue title,
yes tried the same thing
still getting the same error

I am using Xcode version 10.2

**Comment by EraChen233** [comment]
We haven't supported the latest version of Xcode so far. Unexpected errors may occur. We suggest you to reinstall Xcode in a lower version, such as 10.1.

**Comment by SUDARSHANCHAUDHARI** [comment]
ok, I will shift to Xcode 10.1

**Comment by SUDARSHANCHAUDHARI** [comment]
Ok, I just switch back to Xcode version 10.1
iOS-Tagent is working as intended
and I can connect a device to airtest
You can close this ticket

@EraChen233 , thank you for your help and time.
