### ISSUE TITLE
未能载入软件包“WebDriverAgentRunner”。 请尝试重新安装软件包

### ISSUE THREAD

**Issue by laitongxue000** [AirtestProject/iOS-Tagent#34]
![image](https://user-images.githubusercontent.com/24707653/55215304-4a4f5180-5234-11e9-9ff7-55f6e00483d9.png)

**Comment by wss1990122** [comment]
me too

**Comment by qq432591** [comment]
有解决么？

**Comment by zdkic** [comment]
有一樣的錯誤訊息

**Comment by qq432591** [comment]
你有运行 Scripts 下面的 脚本么
@zdkic

**Comment by zdkic** [comment]
剛運行了一下 有報一些錯誤 似乎是少了什麼檔案
```bash
johnchengdeMacBook-Pro:iOS-Tagent johncheng$ ./Scripts/build.sh
Fetching dependencies
*** No Cartfile.resolved found, updating dependencies
Failed to read file or folder at /Users/johncheng/Project/iOS-Tagent/Cartfile: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/johncheng/Project/iOS-Tagent/Cartfile, NSUnderlyingError=0x7fa712437af0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
johnchengdeMacBook-Pro:iOS-Tagent johncheng$ ./Scripts/bootstrap.sh
Fetching dependencies
*** No Cartfile.resolved found, updating dependencies
Failed to read file or folder at /Users/johncheng/Project/iOS-Tagent/Cartfile: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/johncheng/Project/iOS-Tagent/Cartfile, NSUnderlyingError=0x7fc4d7d222b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by qq432591** [comment]
少了Cartfile 这东西应该是， 原本 的WebDriverAgent 项目是有的， 不知道这为何没有是不需要么？

**Comment by qq432591** [comment]
测试了一下 使用Xcode 10.1 是可以解决这个问题！
应该是10.2的问题！

**Comment by dzjwan521** [comment]
@qq432591  我也遇到这样的问题  我不懂ios开发  我手机是ios12.2的 我吧xcode降到10.1的话 我手机就没链接了

**Comment by qq432591** [comment]
@dzjwan521  没连接是什么意思？

**Comment by dzjwan521** [comment]
@432591 打错字了，我原本就是10.1升上来的因为我手机升到ios12.2了，xcode提示要我升10.2

**Comment by qq432591** [comment]
@dzjwan521  WebDriverAgentRunner 的issue中有人也是提问Xcode10.2不能使用 估计得等更新了。

**Comment by EraChen233** [comment]
感谢 @qq432591 指出，我们目前还没有对最新版的xcode进行兼容。所以可能会遇到一些未预知的错误，目前我们是建议先降低xcode版本，等待我们后续的更新。

**Comment by mackxu** [comment]
伸手党 借楼调研下：xcode降级到能跑通ios12.2吗

**Comment by Joyjiji** [comment]
> 感谢 @qq432591 指出，我们目前还没有对最新版的xcode进行兼容。所以可能会遇到一些未预知的错误，目前我们是建议先降低xcode版本，等待我们后续的更新。

哭疗。。。什么时候能解决🙏。。。。Xcode没办法降级。。。这个也没办法用。。。

**Comment by xuyucheng1992** [comment]
> > 感谢@ qq432591指出，我们目前还没有对最新版的Xcode中进行兼容。所以可能会遇到一些未预知的错误，目前我们是建议先降低Xcode的版本，等待我们后续的更新。
> 
> 哭疗......什么时候能解决🙏.... Xcode中没办法降级......这个也没办法用...

参考这个https://blog.csdn.net/auccy/article/details/79763016，下载历史版本的xcode

**Comment by Joyjiji** [comment]
> > > 感谢@ qq432591指出，我们目前还没有对最新版的Xcode中进行兼容。所以可能会遇到一些未预知的错误，目前我们是建议先降低Xcode的版本，等待我们后续的更新。
> > 
> > 
> > 哭疗......什么时候能解决🙏.... Xcode中没办法降级......这个也没办法用...
> 
> 参考这个[https://blog.csdn.net/auccy/article/details/79763016，下载历史版本的xcode](https://blog.csdn.net/auccy/article/details/79763016%EF%BC%8C%E4%B8%8B%E8%BD%BD%E5%8E%86%E5%8F%B2%E7%89%88%E6%9C%AC%E7%9A%84xcode)

404了。。。

**Comment by Joyjiji** [comment]
I find a way to work around this problem.

Xcode 10.2 including the latest XCTest.framework which broken some private API, wda dependent those API .

Xcode keep XCTest.framework at path:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework
So you can find out older XCTest.framework in older Xcode, and replace XCTest.framework in Xcode 10.2.

从wda的GitHub上8来的，亲测有效，大家可以试一下

**Comment by EraChen233** [comment]
@laitongxue000 @qq432591 @zdkic @dzjwan521 @Joyjiji @xuyucheng1992 @mackxu 

iOS-Tagent 已经更新了，现在可以支持新版 Xcode 和最新的iOS 了
