### ISSUE TITLE
Running iOS-Tagent> webdriveragent with Xcode(10.1) results in a signing error.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/iOS-Tagent#37]
Running iOS-Tagent> webdriveragent with Xcode(10.1) results in a signing error.

1. download & iOS-Tagent: iOS-Tagent
2. Execution: ios-Tagent-master> webdriveragent.xcodeproj
3. xcode>  WebFriverAgent run (build  WebDriverAgentRunner: Succeeded)
4.  xcode>  WebFriverAgent> WebDriverAgentRunner: signing error
![KakaoTalk_20190404_093326667](https://user-images.githubusercontent.com/46311868/55521717-d7732a00-56bc-11e9-94a8-d6b2ddff4d82.jpg)

**Comment by EraChen233** [comment]
We provide a solution in README_zh.md. Just follow the steps shown in the picture and change `Product Bundle Identifier` to a unique one.

https://github.com/AirtestProject/iOS-Tagent/blob/master/README_zh.md#%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B

![image](https://user-images.githubusercontent.com/5961185/55528109-4e64ee80-56ce-11e9-8001-943f25728d6a.png)
