### ISSUE TITLE
When I run WebDriverAgent, Build Failed occurs.

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/iOS-Tagent#38]
When I run WebDriverAgent, Build Failed occurs.

1.download & iOS-Tagent: iOS-Tagent
2.Execution: ios-Tagent-master> webdriveragent.xcodeproj
3. xcode> WebFriverAgent> Build Settings > Product Bundle Identifier(com.xxx.webDriverAgent-jjunm)
3.xcode> WebFriverAgent run (build WebDriverAgent: Failed)
4. xcode> WebFriverAgent> WebDriverAgentRunner: signing error

![KakaoTalk_20190404_152113071](https://user-images.githubusercontent.com/46311868/55534109-5df42f80-56ee-11e9-976c-8563e1fe7c36.jpg)

**Comment by EraChen233** [comment]
Apple Developer Certificate is required to deploy iOS-Tagent. Fortunately, Apple now allows us to register with Apple ID without payment.

- Select `Xcode` -> `Preferences` -> `Accounts` -> `Manage Certificates` -> below the left column `+` -> `iOS Development` to login Xcode.
![image](https://user-images.githubusercontent.com/5961185/55534930-38642780-56e8-11e9-998b-d3162be610d9.png)


- After login, you need set up the developer certificate. `WebDriverAgent` -> `WebDriverAgent-Runner` -> `General` -> `Signing` select your certificate
![image](https://user-images.githubusercontent.com/5961185/55534938-3d28db80-56e8-11e9-950b-44f0d80b9d47.png)
