### ISSUE TITLE
构建成功，但是就是不能正确连接手机

### ISSUE THREAD

**Issue by yanghuizhi** [AirtestProject/iOS-Tagent#4]
![image](https://user-images.githubusercontent.com/29268369/44093737-f1a3904e-a006-11e8-9d55-d7161fc50672.png)
，求指导，

**Comment by brantxiong** [comment]
能贴下Xcode窗口的运行log么？

**Comment by jeniva** [comment]
我也遇到了，请问解决了吗

**Comment by yanghuizhi** [comment]
> 我也遇到了，请问解决了吗

目前还没解决

**Comment by brantxiong** [comment]
麻烦给下Xcode debug窗口的log？

**Comment by jeniva** [comment]
我这边可以连接上了，昨天把mac系统更新可，xcode组件也更新了一下，然后今天试了一下居然就连上了，但是录制的时候不知道为什么有时候会重复点击两次

**Comment by brantxiong** [comment]
重复点击两次 具体是指？我这边使用Airtest录制和Poco录制都只会点一次，生成一条点击语句。

**Comment by jeniva** [comment]
poco("8").click()
poco("8").click()
poco("乘").click()
poco("9").click()
poco("加").click()
poco("5").click()
poco("5").click()
我录制的时候我只点了一次8和5，这时候会出现两次，有时候是一次，如果你们都没遇见过的话可能和我鼠标有关系，我在试试吧，有问题会提问的哈，谢谢

**Comment by lsblueabc** [comment]
不一定是这个的错误，但经常突然链接失败，然后报的日志就是请注意iOS-Targent的status

**Comment by brantxiong** [comment]
麻烦贴下Xcode Log窗口的日志？

**Comment by Jamesparagon** [comment]
IOS12.1真机，WDA build success，但是test failed
![image](https://user-images.githubusercontent.com/13159966/48461386-6797fc00-e80e-11e8-98c6-5edfe6af3a8b.png)

**Comment by qiujinwang66** [comment]
![image](https://user-images.githubusercontent.com/49479254/56404387-fb2b9800-6298-11e9-9eb1-e109fa4a901c.png)

**Comment by guomochong** [comment]
我也遇到了，请问解决了吗？怎么解决？

**Comment by EraChen233** [comment]
按照当前信息，无法判断问题原因，烦请提供xcode的log信息。
这个issue长期没有更新，我先暂时关闭了，如果有更多信息的反馈（请重新打开这个issue，或者重新开一个issue）
