### ISSUE TITLE
set up proxy error(iproxy)

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/iOS-Tagent#40]
iphone 6plus(os 10.2) set up proxy error(iproxy)

1.ios-Tagent (WebDriverAgent) set up 
2. set up proxy
- Mac terminal:
$ brew install libimobiledevice
$ iproxy 8100 8100
- waiting for connection: Error Connectiong to device
![KakaoTalk_20190408_151102470](https://user-images.githubusercontent.com/46311868/55702327-429c6380-5a11-11e9-8509-bbb5ec3b6675.jpg)

**Comment by EraChen233** [comment]
Did you run "Test" on iOS-Tagent on Xcode?
Is there any error message in your Xcode console?
What is the version of your Xcode and iPhone?

**Comment by JJunM** [comment]
> Did you run "Test" on iOS-Tagent on Xcode?
 -
![KakaoTalk_20190408_155415800](https://user-images.githubusercontent.com/46311868/55705093-eb01f600-5a18-11e9-8645-aec11beb0751.jpg)

> Is there any error message in your Xcode console?
   -  I ran iOS-Tagent in xcode and successfully deployed the build.
![KakaoTalk_20190408_160701379](https://user-images.githubusercontent.com/46311868/55704932-7a5ad980-5a18-11e9-82ea-23946bc83c13.jpg)
![KakaoTalk_20190408_160700893](https://user-images.githubusercontent.com/46311868/55704939-7e86f700-5a18-11e9-8294-d13a78b64c40.jpg)

> What is the version of your Xcode and iPhone?
   -iphone 6plus(os 10.2)
   -Xcode 10.1

**Comment by EraChen233** [comment]
![image](https://user-images.githubusercontent.com/5961185/55705433-5d6ed800-5a11-11e9-94df-28d94a504846.png)

**Comment by JJunM** [comment]
![KakaoTalk_20190408_164416451](https://user-images.githubusercontent.com/46311868/55707063-a593f780-5a1d-11e9-977f-769b37a5f1ff.jpg)

**Comment by xdc1214** [comment]
您好，
我有同样的问题。终端上编译$ iproxy 8100 8100，一直显示waiting for conncection。 我把iproxy(libimobiledevice)下载到电脑里，打开终端，把autogen.sh拖到终端里，点回车，但显示13行，15行。。。错误。请问是我哪步操作有问题吗？谢谢。
我iphone在xcode里无错误，应用已安装到手机里。

**Comment by xdc1214** [comment]
![log iproxy](https://user-images.githubusercontent.com/7533608/62308295-ba5a3680-b4b7-11e9-8b1c-922aef7731b5.JPG)

**Comment by EraChen233** [comment]
请仔细阅读教程 @xdc1214
