### ISSUE TITLE
iOS Game Automation Error 

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/iOS-Tagent#42]
[setting]
**- xcode webdriveragentrunner test build issues**
<img width="1440" alt="aaa" src="https://user-images.githubusercontent.com/46311868/55845536-40571800-5b7d-11e9-87a6-472799666c7a.png">

- xcode webdriveragentrunner test build warring issues

<img width="1176" alt="issue_01" src="https://user-images.githubusercontent.com/46311868/55846564-19024a00-5b81-11e9-9177-79387e392f16.png">

**- xcode webdriveragentrunner test log**
![sc 012](https://user-images.githubusercontent.com/46311868/55853120-b7e77000-5b9a-11e9-84e4-c77c3a9db0ff.jpg)

**- airtest ide run log**
![이미지 008](https://user-images.githubusercontent.com/46311868/55845499-0c7bf280-5b7d-11e9-86d8-6d205369a059.png)

- version
 iphone 6plus (os 10.2)
 airtestide 1.2.0
 xcode 10.1

[iOS Game Automation Error]
- After connecting airtest with iOS, I ran the game and advanced the automation, but did not recognize the game screen ui.
-  After running an iOS game, capturing an image on the iOS Screen screen captures the other screen. 
- When you press game ui on IOS Screen, you can not select game uI.
- If the game screen rotates from the iPhone, iOS SCREEN does not rotate the screen.
![이미지 010](https://user-images.githubusercontent.com/46311868/55845869-8b255f80-5b7e-11e9-98d0-477da639531a.png)

**Comment by EraChen233** [comment]
same as issue [When running airtest with custom python with MAC aitest ide, an error occurs.](https://github.com/AirtestProject/Airtest/issues/407#issuecomment-497235934)
