### ISSUE TITLE
git项目代码下载失败

### ISSUE THREAD

**Issue by wessonlan** [AirtestProject/iOS-Tagent#44]
[
![image](https://user-images.githubusercontent.com/37354254/56008136-bd18fc00-5d0d-11e9-9907-d915ce4a7cbf.png)
](url)

**Comment by yimelia** [comment]
可能是你所在的网络环境到git的下载服务之间有点问题。
可以留个邮箱我单独给你发一份zip

**Comment by wessonlan** [comment]
> 可能是你所在的网络环境到git的下载服务之间有点问题。
> 可以留个邮箱我单独给你发一份zip
多谢，767760325@qq.com

**Comment by yimelia** [comment]
已发送，请查收。
