### ISSUE TITLE
Xcode10.1无法启动iOS-Tagent

### ISSUE THREAD

**Issue by Yogurt1270** [AirtestProject/iOS-Tagent#45]
![image](https://user-images.githubusercontent.com/8851635/56089160-82f05b80-5ec1-11e9-8cc0-974bcc929218.png)

**Comment by EraChen233** [comment]
截图中的报错信息仅为warning，不影响项目运行，请提供更多报错信息以便我们定位问题

**Comment by Meteorix** [comment]
继续执行下一步操作，遇到问题再贴上来吧

**Comment by EraChen233** [comment]
这个issue长期没有更新，我先暂时关闭了，如果有更多信息的反馈（请重新打开这个issue）
