### ISSUE TITLE
远程通过URL连接设备失败

### ISSUE THREAD

**Issue by IcyW** [AirtestProject/iOS-Tagent#49]
已确认连接无误：
![image](https://user-images.githubusercontent.com/16513834/56706743-aaa8b480-6748-11e9-89d5-996d34f5f272.png)
![image](https://user-images.githubusercontent.com/16513834/56706848-13902c80-6749-11e9-87a1-e99dc0424046.png)

但是AirtestIDE中：连接iOS设备失败，请查阅官网[FAQ](http://airtest.netease.com/docs/cn/2_device_connection/4_ios_connection.html)获得更多信息。

![image](https://user-images.githubusercontent.com/16513834/56706773-c57b2900-6748-11e9-84f9-3ad6d338cb1f.png)
终端：

> TypeError: invalid result from ConnectPhoneThread.run()
Sentry responded with an error: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。> (url: http://web-server-airtestide-airtestide.tantive4-sentry.cube-dg.nie.netease.com:9009/api/3/store/)
{'event_id': '2ff80fb6ba78464d8603ebe0ae6c196d',
 'exception': {'values': [{'module': 'builtins',
                           'stacktrace': {'frames': []},
                           'type': 'TypeError',
                           'value': 'invalid result from '
                                    'ConnectPhoneThread.run()'}]},
 'extra': {'sys.argv': ["'E:\\AirtestIDE_2019-04-16_py3_win64\\AirtestIDE.exe'"]},
 'level': 40,
 'message': 'TypeError: invalid result from ConnectPhoneThread.run()',
 'modules': {'python': '3.6.8'},
 'platform': 'python',
 'project': '3',
 'release': '1.2.1',
 'server_name': 'AirtestIDE',
 'tags': {'bit': '64bit', 'debug': 'RELEASE', 'platform': 'Windows'},
 'time_spent': None,
 'timestamp': '2019-04-25T02:51:37Z'}
['TypeError: invalid result from ConnectPhoneThread.run()']

**Comment by yimelia** [comment]
用的是wdaproxy还是iproxy?

**Comment by IcyW** [comment]
> 用的是wdaproxy还是iproxy?

是wdaproxy

**Comment by EraChen233** [comment]
麻烦提供一下Xcode版本，iOS版本，Xcode输出以及wdaproxy的输出

**Comment by EraChen233** [comment]
这个issue长期没有更新，我先暂时关闭了，如果有更多信息的反馈（请重新打开这个issue）
