### ISSUE TITLE
WebDriverAgent-Runner Build distribution issue

### ISSUE THREAD

**Issue by JJunM** [AirtestProject/iOS-Tagent#50]
xcode: 10.2.1
MacOS: 10.14.4
iOS: iphone 6s (12.2)

<img width="1168" alt="aaa" src="https://user-images.githubusercontent.com/46311868/56716682-e73ed500-6775-11e9-8f4f-2022cd4d0255.png">

**Comment by guomochong** [comment]
我也遇到了这个问题，可能是xcode 版本过高导致
