### ISSUE TITLE
Xcode10.2.1无法启动ios-Tagent

### ISSUE THREAD

**Issue by bluepang** [AirtestProject/iOS-Tagent#51]
Showing Recent Messages
WebDriverAgentRunner-Runner.app (5155) encountered an error (Failed to load the test bundle. (Underlying error: 未能载入软件包“WebDriverAgentRunner”。. 未能载入该软件包。. dlopen(/var/containers/Bundle/Application/60CD6E95-7015-4B0D-8D1F-6A1DA92C9689/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner, 265): Symbol not found: _OBJC_CLASS_$_XCEventGenerator
  Referenced from: /private/var/containers/Bundle/Application/60CD6E95-7015-4B0D-8D1F-6A1DA92C9689/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Expected in: /private/var/containers/Bundle/Application/60CD6E95-7015-4B0D-8D1F-6A1DA92C9689/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest
 in /private/var/containers/Bundle/Application/60CD6E95-7015-4B0D-8D1F-6A1DA92C9689/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib))

**Comment by bluepang** [comment]
手机是iPhone XR ios12.2，Xcode升级前是可以用的，最近升级了

**Comment by bluepang** [comment]
![报错](https://user-images.githubusercontent.com/25786859/56806907-e1bdb980-685f-11e9-871f-4cd840805ec1.png)

**Comment by bluepang** [comment]
build成功了，但是test就失败了

**Comment by EraChen233** [comment]
iOS-Tagent 目前还未对Xcode 12.1进行支持，因此可能会发生一些未知错误，建议对Xcode进行降级，等待iOS-Tagent更新

**Comment by bluepang** [comment]
ok

**Comment by felixhelucky** [comment]
有计划什么时候可以支持Xcode10.2.1么？
我现在用Xcode10.2.1 + iOS12.2, 也是出现这个问题

**Comment by dzjwan521** [comment]
你xcode降级后手机12.2还能用吗

**Comment by bluepang** [comment]
我降级后换了11.4.1版本的手机来测试

**Comment by felixhelucky** [comment]
我现在Xcode降级到10.1，可以用iOS 12.1.4
但是Xcode10.1+iOS 12.2，就不能用， 提示不支持

**Comment by ldy1691github** [comment]
白看了，Xcode10.2不支持，没法用

**Comment by felixhelucky** [comment]
什么时候可以支持iOS12.2?

**Comment by EraChen233** [comment]
@bluepang @felixhelucky @dzjwan521 @ldy1691github 

iOS-Tagent 已经更新了，现在可以支持新版 Xcode 和最新的iOS 了
