### ISSUE TITLE
Build Successful, Test Failed

### ISSUE THREAD

**Issue by phantomsom** [AirtestProject/iOS-Tagent#56]
https://github.com/AirtestProject/iOS-Tagent
![image](https://user-images.githubusercontent.com/19833754/57282708-307d1600-70e0-11e9-9553-547f26676c18.png)

I followed the steps provided in the above link, build is successful but test failed. I put ios tagent in the same directory as my airtest project.

I got 3 warnings,
![image](https://user-images.githubusercontent.com/19833754/57282421-9917c300-70df-11e9-8b8c-fa08c6f8d425.png)

Changed project bundle identifier
![image](https://user-images.githubusercontent.com/19833754/57282471-b3ea3780-70df-11e9-8404-79f7dac46084.png)

Signing looks okay
![image](https://user-images.githubusercontent.com/19833754/57282557-e136e580-70df-11e9-8b45-3f91e86d0a79.png)

Device is connected to the device that is plugged in by USB on the iMac
![image](https://user-images.githubusercontent.com/19833754/57282746-3ecb3200-70e0-11e9-91a4-9b4a2dd71fef.png)

WebDriverAgentRunner
My MacOs Version : macOS Mojave Version 10.14.4, iMac (21.5-inch, Late 2012)
My iOS device : iOS Version 12.2, iPad Pro (12.9 Inch, 3rd Generation) 
My Xcode Version : Version 10.2.1

Below is the error message found on xcode
2019-05-07 15:43:45.147790+0800 WebDriverAgentRunner-Runner[1319:900337] [ApplicationLifecycle] Windows were created before application initialzation completed. This may result in incorrect visual appearance.
2019-05-07 15:43:45.160506+0800 WebDriverAgentRunner-Runner[1319:900337] Running tests...
2019-05-07 15:43:45.347343+0800 WebDriverAgentRunner-Runner[1319:900337] The bundle “WebDriverAgentRunner” couldn’t be loaded. Try reinstalling the bundle.
2019-05-07 15:43:45.347625+0800 WebDriverAgentRunner-Runner[1319:900337] (dlopen(/var/containers/Bundle/Application/F5321847-CC68-419D-B075-D2EDD4CC9623/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner, 265): Symbol not found: _OBJC_CLASS_$_XCEventGenerator
  Referenced from: /private/var/containers/Bundle/Application/F5321847-CC68-419D-B075-D2EDD4CC9623/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Expected in: /private/var/containers/Bundle/Application/F5321847-CC68-419D-B075-D2EDD4CC9623/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest
 in /private/var/containers/Bundle/Application/F5321847-CC68-419D-B075-D2EDD4CC9623/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib)

**Comment by EraChen233** [comment]
iOS-Tagent does not support the latest version of Xcode (10.2.1) yet. Unexpected errors will occur. We will publish new version after development is complete.

**Comment by phantomsom** [comment]
Thanks for your fast response, Era
Does that mean I can run iOS-Tagent on the previous version, Xcode 10.2 instead of XCode 10.2.1?

**Comment by EraChen233** [comment]
For now, yes

**Comment by phantomsom** [comment]
Hello Era, 
I installed Xcode version 10.2, run the test using the project found in ios-Tagent, and still get the same error message  as above.

XCode version changed
![image](https://user-images.githubusercontent.com/19833754/57348941-b6559b80-718a-11e9-8c9f-ad63ad93609a.png)

Signing looks ok
![image](https://user-images.githubusercontent.com/19833754/57348955-cbcac580-718a-11e9-97e5-2f61c547afdb.png)

![image](https://user-images.githubusercontent.com/19833754/57348978-ddac6880-718a-11e9-89d4-7c64341fc856.png)
Schema and destination device selected correctly

Project Identifier changed
![image](https://user-images.githubusercontent.com/19833754/57348921-a5a52580-718a-11e9-889e-7b935cd52677.png)

Error message, same as above
![image](https://user-images.githubusercontent.com/19833754/57348214-ddf73480-7187-11e9-89d7-316e38614a45.png)

The bundle “WebDriverAgentRunner” couldn’t be loaded. Try reinstalling the bundle. How do I reinstall the bundle?

**Comment by EraChen233** [comment]
Try Xcode 10.1

**Comment by phantomsom** [comment]
Thank you, I'm finally able to make airtest connect to my iOS device!
Using Xcode 10.1, and iOS version 12.0

But after connect to my iOS device on AirtestIDE
1) I ran my project on my game and I got a new error

https://github.com/AirtestProject/iOS-Tagent/issues/57

**Comment by EraChen233** [comment]
@phantomsom 
We have released a new version. Update the latest iOS-Tagent and you will be able to test latest iOS with to test latest Xcode.
