### ISSUE TITLE
请问project-test启动项目时为啥会有这个警告，详见图

### ISSUE THREAD

**Issue by lvorcool** [AirtestProject/iOS-Tagent#58]
环境参数
macOS Mojave10.14.4 (18E226)
xcode10.1 (10B61)
iOS10.2.1
提示build success
test一直在进行中，等了五六分钟还没完成

![image](https://user-images.githubusercontent.com/21286480/57507736-3407db80-7332-11e9-93a6-8987f2603dd6.png)

**Comment by EraChen233** [comment]
Warning不用管，Build sucess之后，继续下一步 `Test`就可以了，检查Log输出是否有以下信息

![image](https://user-images.githubusercontent.com/5961185/57508049-08d1bc00-7333-11e9-851a-be1a31b1d542.png)

**Comment by lvorcool** [comment]
@EraChen233 感谢您这么速度的答复，现在问题就是test一直在进行中，已经十分钟了，还没结果，不知道啥情况~~
![image](https://user-images.githubusercontent.com/21286480/57508259-9f9e7880-7333-11e9-8621-59bea70ba0b1.png)

**Comment by EraChen233** [comment]
查看log 窗口输出

![image](https://user-images.githubusercontent.com/5961185/57508765-07a18e80-7335-11e9-941f-e0e23dc3b27f.png)

**Comment by lvorcool** [comment]
> 查看log 窗口输出
> 
> ![image](https://user-images.githubusercontent.com/5961185/57508765-07a18e80-7335-11e9-941f-e0e23dc3b27f.png)

 @EraChen233 您好，一直卡在这
![image](https://user-images.githubusercontent.com/21286480/57509187-29e7dc00-7336-11e9-8c12-15314f4dc647.png)

我电脑的hosts没设置啥
![image](https://user-images.githubusercontent.com/21286480/57509268-61ef1f00-7336-11e9-8390-7914af7d9424.png)

**Comment by EraChen233** [comment]
请注意看部署教程
https://github.com/AirtestProject/iOS-Tagent/blob/master/README_zh.md

![image](https://user-images.githubusercontent.com/5961185/57509344-9367ea80-7336-11e9-9e9b-80d42183a460.png)

**Comment by lvorcool** [comment]
> 请注意看部署教程
> https://github.com/AirtestProject/iOS-Tagent/blob/master/README_zh.md
> 
> ![image](https://user-images.githubusercontent.com/5961185/57509344-9367ea80-7336-11e9-9e9b-80d42183a460.png)

我明白了，这样表示项目启动成功了，就OK了，我还以为需要等待返回test success呢，谢谢您了

**Comment by xdc1214** [comment]
你好, 我和你的情况一样, 只是把iphone连到windows电脑上, 打开airtest, 连接ios设备, 总显示失败. 在手机通用/设备管理确实看到开发者应用安装成功了. 请问你在windows电脑上成功连接iphone了吗?谢谢.

**Comment by xdc1214** [comment]
xcode10.3
IOS12.2
iphone 6s

**Comment by EraChen233** [comment]
@xdc1214 注意看教程，如有错误，麻烦把xcode log窗口的错误信息贴出来

**Comment by xdc1214** [comment]
谢谢您这么快的回复. 我是按教程一步步做的. 多做的一步是改了IOS Deployment Target, 改成我手机的系统号. 

xcode的log和教程里的一样:

![Jietu20190731-172629](https://user-images.githubusercontent.com/7533608/62278615-076be780-b47b-11e9-984d-1d039b838422.jpg)

只是xcode最上面一直显示testing:

![Jietu20190801-144340](https://user-images.githubusercontent.com/7533608/62278685-266a7980-b47b-11e9-98a4-16580b7f03fe.jpg)

然后我把iphone从苹果电脑上拔下插到windows系统的电脑里, 打开airtest, 连接ios设备, lairtest里log显示 

![Capture](https://user-images.githubusercontent.com/7533608/62278876-89f4a700-b47b-11e9-9818-1ac0fb1d7149.JPG)

我看xcode里有warning, 就检查了一下, 发现有个地址不存在

![Jietu20190801-144105](https://user-images.githubusercontent.com/7533608/62278957-b6102800-b47b-11e9-9a49-9beb8bf57ef0.jpg)

我把第二行的地址删了, 又重新安装了一次, 没有warning, 但在airtest里还是一样的log

感谢您的解答

**Comment by EraChen233** [comment]
这句话是什么意思？iPhone要一直连着Mac电脑的呀

![image](https://user-images.githubusercontent.com/5961185/62279278-59613d00-b47c-11e9-94c1-0308171b5614.png)

**Comment by xdc1214** [comment]
我看airtest教程上写: 使用xcode部署 iOS-Tagent 成功后，能够在mac或windows机器上连接到iOS手机。
我想在windows机器上连接到ios手机, 请问我该如何操作.
谢谢

**Comment by EraChen233** [comment]
![image](https://user-images.githubusercontent.com/5961185/62280049-c88b6100-b47d-11e9-83e7-bca14aa15c09.png)

**Comment by xdc1214** [comment]
明白了, 感谢您的解答.
