### ISSUE TITLE
Unhandled endpoint: / -- http://127.0.0.1:8100/ with parameters { wildcards = ( "" ); }

### ISSUE THREAD

**Issue by ca-ssiee** [AirtestProject/iOS-Tagent#59]
webDriverAgent安装并运行成功后打开127.0.0.1:8100遇到错误
{
value: "Unhandled endpoint: / -- http://127.0.0.1:8100/ with parameters { wildcards = ( "" ); }",
sessionId: "46DCAB5E-6446-43BB-BB89-3AFC4E864704",
status: 1
}

控制面板显示如下：
recv failed: Resource temporarily unavailable
accepted connection, fd = 6
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 1 (serial: 2b0bff559ac1c97328c7a41189fa327a038b8fff), port 8100
run_ctos_loop: fd = 6
run_stoc_loop: fd = 6
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted

**Comment by EraChen233** [comment]
你是用浏览器打开的吗？
iOS-Tagent 启动之后，启动iproxy，然后使用浏览器可以访问
http://127.0.0.1:8100/status  或者  http://127.0.0.1:8100/inspector

IDE 连接iOS 则在设备连接窗口，输入 http://127.0.0.1:8100 并点击“connect” 按钮
