### ISSUE TITLE
IOS12 设备频繁掉线

### ISSUE THREAD

**Issue by skiponmyhands** [AirtestProject/iOS-Tagent#67]
真机测试时，设备经常断开连接。而且iproxy的输出显示有大量的循环请求，不知道有什么影响。
iproxy输出：
ng connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
accepted connection, fd = 32
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 32
run_stoc_loop: fd = 32
recv failed: Resource temporarily unavailable
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
accepted connection, fd = 40
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 40
run_stoc_loop: fd = 40
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 10
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 10
run_stoc_loop: fd = 10
recv failed: Resource temporarily unavailable
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
accepted connection, fd = 37
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 37
run_stoc_loop: fd = 37
recv failed: Resource temporarily unavailable
accepted connection, fd = 18
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
recv failed: Resource temporarily unavailable
run_ctos_loop: fd = 18
run_stoc_loop: fd = 18
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 17
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 17
run_stoc_loop: fd = 17
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
waiting for connection
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
accepted connection, fd = 42
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 42
run_stoc_loop: fd = 42
recv failed: Resource temporarily unavailable
accepted connection, fd = 5
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 5
recv failed: Resource temporarily unavailable
run_stoc_loop: fd = 5
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 5
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 5
run_stoc_loop: fd = 5
recv failed: Resource temporarily unavailable
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
accepted connection, fd = 32
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 32
run_stoc_loop: fd = 32
recv failed: Resource temporarily unavailable
accepted connection, fd = 8
waiting for connection
recv failed: Resource temporarily unavailable
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 8
run_stoc_loop: fd = 8
accepted connection, fd = 11
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 11
run_stoc_loop: fd = 11
recv failed: Resource temporarily unavailable
accepted connection, fd = 8
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 8
run_stoc_loop: fd = 8
recv failed: Resource temporarily unavailable
accepted connection, fd = 11
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 2 (serial: 9acd4d02222d0ab1c561c0244f3458e17c172226), port 8100
run_ctos_loop: fd = 11
run_stoc_loop: fd = 11

**Comment by EraChen233** [comment]
iproxy 输出没有关系，这个是因为IDE在不断刷新手机屏幕或者poco在刷新UI树
频繁掉线的情况，你注意过规律吗？或者有哪个操作一定会导致掉线吗？

**Comment by skiponmyhands** [comment]
暂时没有发现什么规律哎  很不稳定  我用脚本进行一些操作或者手动操作几步后 等待一会就会掉线，而且重新连接也失败，很头疼

**Comment by EraChen233** [comment]
你的xcode和iOS版本信息是什么？我尝试复现一下
掉线表现在什么地方？IDE出现异常？xcode的log窗口有报错吗

**Comment by skiponmyhands** [comment]
xcode9.4 IOS12.3.1
有时候是IDE内无法操作手机
刚刚碰到一个情况是：刚连接上手机，IDE点击进入app后，IDE内screen窗口无法操作，然后手机的webDriverAgent自动重启 一直处于黑屏状态
xcodelog：
2019-07-08 18:07:05.800059+0800 WebDriverAgentRunner-Runner[4928:466628] Enqueue Failure: Snapshot timed out after 60.0s /Users/migu/Downloads/iOS-Tagent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =   302.48s         Snapshot accessibility hierarchy for app with pid 4883
    t =   302.71s         Find the Window
    t =   302.72s             Snapshot accessibility hierarchy for app with pid 4883
    t =   302.91s         Find the Window
    t =   302.92s             Snapshot accessibility hierarchy for app with pid 4883
    t =   303.06s         Snapshot accessibility hierarchy for app with pid 4883
    t =   303.17s         Find the Window
    t =   303.18s             Snapshot accessibility hierarchy for app with pid 4883
    t =   303.30s         Find the Window
    t =   303.30s             Snapshot accessibility hierarchy for app with pid 4883
    t =   303.43s         Press and drag from Window[0.00, 0.00] -> (188.4, 562.2) to Window[0.00, 0.00] -> (219.9, 393.0)
    t =   303.44s             Wait for com.apple.Preferences to idle
    t =   303.44s             Find the Window
    t =   303.44s                 Snapshot accessibility hierarchy for app with pid 4883
    t =   303.67s             Synthesize event
    t =   303.69s                 Find the Window
    t =   303.69s                     Snapshot accessibility hierarchy for app with pid 4883
    t =   303.84s                 Find the Window
    t =   303.84s                     Snapshot accessibility hierarchy for app with pid 4883
    t =   305.22s             Wait for com.apple.Preferences to idle
    t =   305.63s         Snapshot accessibility hierarchy for app with pid 4883
    t =   305.76s         Find the Window
    t =   305.77s             Snapshot accessibility hierarchy for app with pid 4883
    t =   305.90s         Find the Window
    t =   305.90s             Snapshot accessibility hierarchy for app with pid 4883
    t =   306.04s         Snapshot accessibility hierarchy for app with pid 4883
    t =   306.16s         Find the Window
    t =   306.16s             Snapshot accessibility hierarchy for app with pid 4883
    t =   306.29s         Find the Window
    t =   306.29s             Snapshot accessibility hierarchy for app with pid 4883
    t =   306.43s         Press and drag from Window[0.00, 0.00] -> (170.2, 432.2) to Window[0.00, 0.00] -> (149.2, 278.2)
    t =   306.43s             Wait for com.apple.Preferences to idle
    t =   306.54s             Find the Window
    t =   306.54s                 Snapshot accessibility hierarchy for app with pid 4883
    t =   306.80s             Synthesize event
    t =   306.81s                 Find the Window
    t =   306.82s                     Snapshot accessibility hierarchy for app with pid 4883
    t =   306.98s                 Find the Window
    t =   306.98s                     Snapshot accessibility hierarchy for app with pid 4883
    t =   308.29s             Wait for com.apple.Preferences to idle
    t =   308.80s         Snapshot accessibility hierarchy for app with pid 52
    t =   308.89s         Find the Window
    t =   308.89s             Snapshot accessibility hierarchy for app with pid 52
    t =   308.99s         Find the Window
    t =   308.99s             Snapshot accessibility hierarchy for app with pid 52
    t =   309.09s         Snapshot accessibility hierarchy for app with pid 52
    t =   309.16s         Find the Window
    t =   309.17s             Snapshot accessibility hierarchy for app with pid 52
    t =   309.26s         Find the Window
    t =   309.26s             Snapshot accessibility hierarchy for app with pid 52
    t =   309.36s         Press and drag from Window[0.00, 0.00] -> (134.8, 555.5) to Window[0.00, 0.00] -> (118.6, 394.9)
    t =   309.36s             Wait for com.apple.springboard to idle
    t =   309.37s             Find the Window
    t =   309.37s                 Snapshot accessibility hierarchy for app with pid 52
    t =   309.56s             Synthesize event
    t =   309.57s                 Find the Window
    t =   309.57s                     Snapshot accessibility hierarchy for app with pid 52
    t =   309.67s                 Find the Window
    t =   309.68s                     Snapshot accessibility hierarchy for app with pid 52
    t =   310.93s             Wait for com.apple.springboard to idle
2019-07-08 18:07:26.931581+0800 WebDriverAgentRunner-Runner[4928:466628] *** Assertion failure in +[FBApplication fb_activeApplication], /Users/airtest_mac_mini/Desktop/airtest/wda-eov/WebDriverAgentLib/FBApplication.m:43
2019-07-08 18:07:26.944469+0800 WebDriverAgentRunner-Runner[4928:466628] *** Assertion failure in +[FBApplication fb_activeApplication], /Users/airtest_mac_mini/Desktop/airtest/wda-eov/WebDriverAgentLib/FBApplication.m:43
2019-07-08 18:07:26.962064+0800 WebDriverAgentRunner-Runner[4928:466628] *** Assertion failure in +[FBApplication fb_activeApplication], /Users/airtest_mac_mini/Desktop/airtest/wda-eov/WebDriverAgentLib/FBApplication.m:43
2019-07-08 18:07:26.977530+0800 WebDriverAgentRunner-Runner[4928:466628] *** Assertion failure in +[FBApplication fb_activeApplication], /Users/airtest_mac_mini/Desktop/airtest/wda-eov/WebDriverAgentLib/FBApplication.m:43
2019-07-08 18:07:26.993763+0800 WebDriverAgentRunner-Runner[4928:466628] *** Assertion failure in +[FBApplication fb_activeApplication], /Users/airtest_mac_mini/Desktop/airtest/wda-eov/WebDriverAgentLib/FBApplication.m:43
2019-07-08 18:07:43.328354+0800 WebDriverAgentRunner-Runner[4928:466628] *** Assertion failure in +[FBApplication fb_activeApplication], /Users/airtest_mac_mini/Desktop/airtest/wda-eov/WebDriverAgentLib/FBApplication.m:43
2019-07-08 18:07:45.049094+0800 WebDriverAgentRunner-Runner[4928:466628] *** Assertion failure in +[FBApplication fb_activeApplication], /Users/airtest_mac_mini/Desktop/airtest/wda-eov/WebDriverAgentLib/FBApplication.m:43
2019-07-08 18:08:16.416505+0800 WebDriverAgentRunner-Runner[4928:466628] *** Assertion failure in +[FBApplication fb_activeApplication], /Users/airtest_mac_mini/Desktop/airtest/wda-eov/WebDriverAgentLib/FBApplication.m:43
2019-07-08 18:08:18.495882+0800 WebDriverAgentRunner-Runner[4928:466628] *** Assertion failure in +[FBApplication fb_activeApplication], /Users/airtest_mac_mini/Desktop/airtest/wda-eov/WebDriverAgentLib/FBApplication.m:43
2019-07-08 18:09:42.665559+0800 WebDriverAgentRunner-Runner[4928:466628] *** Assertion failure in +[FBApplication fb_activeApplication], /Users/airtest_mac_mini/Desktop/airtest/wda-eov/WebDriverAgentLib/FBApplication.m:43

**Comment by EraChen233** [comment]
xcode9.4 可以支持 IOS12.3.1？

**Comment by skiponmyhands** [comment]
我下载了12.3真机调试包  然后放在了xcode的DeviceSupport目录下，可以启动webdriverAgent，是因为xcode版本问题吗

**Comment by EraChen233** [comment]
如果对iOS系统没要求，可以换一个设备试一下，我先查一下你前面发的log日志
如果有别的错误信息，或者截图，麻烦也贴出来哦，可以帮助我们查找问题

**Comment by skiponmyhands** [comment]
嗯   好的  IDE内screen窗口经常性的卡住（手机屏幕也无法操作）  http://127.0.0.1:8100/status http://localhost:8100/source?format=json  http://127.0.0.1:8100/inspector访问的话也一直加载不出来       我换个低版本IOS试下

**Comment by skiponmyhands** [comment]
换了个IOS11.1    目前来看蛮正常的。。

**Comment by EraChen233** [comment]
好的，我晚点仔细查查

**Comment by xiaoyma** [comment]
我的ios12也有同样的问题，ios11设备，通过 http://127.0.0.1:8100去链接也会掉线。
这里我尝试用 http://iphone对应的IP:8100就很稳定，没断过，很奇怪

**Comment by xiaoyma** [comment]
我还尝试把代理转发工具usbmuxd换成mobiledevice，试用一天了，没有再出现脚本执行中断的情况，希望对你有用

**Comment by AndreRao** [comment]
> 我还尝试把代理转发工具usbmuxd换成mobiledevice，试用一天了，没有再出现脚本执行中断的情况，希望对你有用

hello,请问下具体如何操作

**Comment by zhum26zhum** [comment]
@AndreRao 建议使用wdaproxy作为转发工具

**Comment by zhum26zhum** [comment]
iOS-Tagent 已更新，支持最新版xcode 11
