### ISSUE TITLE
打开获取不到元素

### ISSUE THREAD

**Issue by meihaoyidian** [AirtestProject/iOS-Tagent#74]
![image](https://user-images.githubusercontent.com/26756176/62351553-6cd1de00-b538-11e9-8c72-672379e81e27.png)

**Comment by EraChen233** [comment]
network 看一下screen请求返回的是什么内容

**Comment by meihaoyidian** [comment]
@EraChen233   返回的是，请教下这该怎么处理
![image](https://user-images.githubusercontent.com/26756176/62351948-87588700-b539-11e9-8333-e15f208bb48e.png)

**Comment by EraChen233** [comment]
orientation 的请求是个bug，不过airtest暂时没用到这个接口，可以不用管，你现在是能正常使用？

**Comment by meihaoyidian** [comment]
> orientation 的请求是个bug，不过airtest暂时没用到这个接口，可以不用管，你现在是能正常使用？

@EraChen233 请问有具体的教程么？现在不能正常使用。我再mac上

**Comment by EraChen233** [comment]
https://github.com/AirtestProject/iOS-Tagent/blob/master/Introduction/README_zh.md

**Comment by meihaoyidian** [comment]
> https://github.com/AirtestProject/iOS-Tagent/blob/master/Introduction/README_zh.md

好的，谢谢。那我需要下载AirtestIDE试试
