### ISSUE TITLE
wda.WDAError: WDAError(status=889, value=Application is not running, possibly crashed)

### ISSUE THREAD

**Issue by AndreRao** [AirtestProject/iOS-Tagent#78]
Xcode 10.3 
iOS 12.2

WDA经常crash，
ide提示：wda.WDAError: WDAError(status=889, value=Application is not running, possibly crashed)

Xcode提示：
    t =   356.75s Find: Children matching type Any
    t =   356.75s Find: Element at index 7
    t =   356.75s Snapshot accessibility hierarchy for app with pid 331
    t =   356.75s Find: Children matching type Any
    t =   356.75s Snapshot accessibility hierarchy for app with pid 331
    t =   356.75s Snapshot accessibility hierarchy for app with pid 331
    t =   356.81s Snapshot accessibility hierarchy for app with pid 331

端口提示：
Requesting connecion to device handle == 7 (serial: 00008020-001334DE0AF2002E), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 7 (serial: 00008020-001334DE0AF2002E), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 7 (serial: 00008020-001334DE0AF2002E), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 7 (serial: 00008020-001334DE0AF2002E), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 7 (serial: 00008020-001334DE0AF2002E), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable

**Comment by zhum26zhum** [comment]
iOS-Tagent 已更新，支持最新版xcode 11
