### ISSUE TITLE
build 失败

### ISSUE THREAD

**Issue by alexhjb001** [AirtestProject/iOS-Tagent#79]
xcode ： 10.0 
ios ： 10.0.3.4
![Screen Shot 2019-08-21 at 1 41 19 PM](https://user-images.githubusercontent.com/53072613/63410814-b9695480-c426-11e9-974e-2eb9556411f0.png)

**Comment by EraChen233** [comment]
请仔细查看文档和教程
https://github.com/AirtestProject/iOS-Tagent/blob/master/Introduction/question_zh.md#buddle-identifier

**Comment by alexhjb001** [comment]
谢谢
