### ISSUE TITLE
iOS-Tagent只显示1/4屏幕

### ISSUE THREAD

**Issue by qq-kof** [AirtestProject/iOS-Tagent#84]
ios启动proxy后，inspector和AirtestIDE都只显示左上四分之一的屏幕；android是正常的。请问是什么原因？iPhone6s ios 10.2
![1566916005801](https://user-images.githubusercontent.com/54588535/63780401-a371fd00-c91a-11e9-8040-bed8f70a4f05.jpg)

**Comment by EraChen233** [comment]
iOS和xcode版本是？

**Comment by qq-kof** [comment]
ios: iphone 6s 10.2
xcode: 10.3

**Comment by EraChen233** [comment]
iOS版本较低，用xcode10.1吧
