### ISSUE TITLE
IOS 12.4.1系统 ios-agent构建成功，真机连接成功，调用API失败，start_app()报错，requests.exceptions.ReadTimeout

### ISSUE THREAD

**Issue by agoraHan** [AirtestProject/iOS-Tagent#87]
脚本：
  def test_getversion(self):
        start_app("XXX")
ios 11和ios12都执行这个脚本，ios 12.4.1的系统执行后可以正常启动APP 但是之后会报错：
`E               requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8100): Read timed out. (read timeout=60.0)`

**Comment by EraChen233** [comment]
你的xcode版本是多少？现在iOS-Tagent能支持的最高版Xcode为 10.2.1

**Comment by agoraHan** [comment]
XCode 10.3
不过 跑ios 11的手机没遇到这个问题

**Comment by EraChen233** [comment]
XCode 10.3 暂不支持

**Comment by agoraHan** [comment]
这个预计什么时候可以支持呢

**Comment by EraChen233** [comment]
我们会尽快安排的这个工作的

**Comment by agoraHan** [comment]
xcode 换成了10.2.1
在iPhone X（12.4.1）上也会出现这个报错
对ios的系统也是有要求吗？
iPhone 6（ios 11.3.1）是没有这个问题

**Comment by agoraHan** [comment]
facebook-wda降级到0.2.2可以解决该问题
