### ISSUE TITLE
airtestidea连接失败

### ISSUE THREAD

**Issue by zengjia110** [AirtestProject/iOS-Tagent#93]
<img width="1210" alt="屏幕快照 2019-09-29 下午1 34 50" src="https://user-images.githubusercontent.com/34120151/65826873-73719d00-e2be-11e9-8177-8589fd057fac.png">
<img width="1004" alt="屏幕快照 2019-09-29 下午1 35 13" src="https://user-images.githubusercontent.com/34120151/65826874-75d3f700-e2be-11e9-8a5c-88b09a7c7f7d.png">
图一的 Tree of Elements和Inspector为空 请问是否正常 然后idea连接 地址 显示failed

**Comment by zengjia110** [comment]
airtestidea连接时 iproxy控制台显示 recv failed: Resource temporarily unavailable
我的机型时iphone xr

**Comment by EraChen233** [comment]
xcode版本是多少？

**Comment by zengjia110** [comment]
> xcode版本是多少？

xcode -> 11.0
macos -> 10.14.6

**Comment by EraChen233** [comment]
xcode 11目前还不支持哈
