### ISSUE TITLE
iOS-Tagent无法git clone本地，git@github.com: Permission denied (publickey)

### ISSUE THREAD

**Issue by duxia001** [AirtestProject/iOS-Tagent#95]
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by EraChen233** [comment]
ssh 和 Https都不行？
```
git clone git@github.com:AirtestProject/iOS-Tagent.git
git clone https://github.com/AirtestProject/iOS-Tagent.git
```

**Comment by duxia001** [comment]
> ssh 和 Https都不行？
> 
> ```
> git clone git@github.com:AirtestProject/iOS-Tagent.git
> git clone https://github.com/AirtestProject/iOS-Tagent.git
> ```

给留给联系方式哇，我通过下载zip的包下载下来了，但是有一些调试ios的问题，需要咨询一下，这个提bug太慢了

**Comment by EraChen233** [comment]
可以加一下我们的qq群
AirtestProject讨论2群 1017250147
