### ISSUE TITLE
xcode编译成功，启动本地代理连接手机报错

### ISSUE THREAD

**Issue by duxia001** [AirtestProject/iOS-Tagent#97]
waiting for connection
accepted connection, fd = 4
waiting for connection
accepted connection, fd = 5
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 232 (serial: 1babf288f70314388c464b91350568cf023e8fa1), port 8100
Number of available devices == 1
Requesting connecion to device handle == 232 (serial: 1babf288f70314388c464b91350568cf023e8fa1), port 8100
Error connecting to device!
Error connecting to device!
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 232 (serial: 1babf288f70314388c464b91350568cf023e8fa1), port 8100
Error connecting to device!

**Comment by EraChen233** [comment]
xcode版本和iOS版本是多少？

**Comment by EraChen233** [comment]
因为长时间不回复，这个issue我先关了，如果还有问题，整体一下情况，重新提个issue吧
