### ISSUE TITLE
i can not  see iPhone screen projected on the browser by visiting http://127.0.0.1:8100/inspector . The IDC is either. Thanks for your help , waiting  for  your reply.

### ISSUE THREAD

**Issue by luoting0323** [AirtestProject/iOS-Tagent#98]
![image](https://user-images.githubusercontent.com/56343996/66572221-271e3b00-eba3-11e9-9032-8a41c4ac44b0.png)
![image](https://user-images.githubusercontent.com/56343996/66572238-33a29380-eba3-11e9-80b4-e27f39429efe.png)

**Comment by EraChen233** [comment]
What is the version of your xcode and ios os?

**Comment by EraChen233** [comment]
Duplicate of #99
