### ISSUE TITLE
使用ide无法看到动态的手机屏幕，访问http://127.0.0.1:8100/inspector看到的也是白屏。补充：xcode编译通过，iOS-Tagent也成功启动。iphone使用的iOS9-11的系统，都无法看到屏幕投影。mac版本macos-catalina 10.15。辛苦各位路过的大佬施以援手，万分感谢🙏

### ISSUE THREAD

**Issue by luoting0323** [AirtestProject/iOS-Tagent#99]
![image](https://user-images.githubusercontent.com/56343996/66572221-271e3b00-eba3-11e9-9032-8a41c4ac44b0.png)
![image](https://user-images.githubusercontent.com/56343996/66572238-33a29380-eba3-11e9-80b4-e27f39429efe.png)

**Comment by EraChen233** [comment]
xcode版本是多少？xcode的log窗口输出什么？

**Comment by luoting0323** [comment]
> xcode版本是多少？xcode的log窗口输出什么？

xcode版本：Version 11.1 (11A1027)
xcodelog如下：
![image](https://user-images.githubusercontent.com/56343996/66574405-bc6efe80-eba6-11e9-8408-3f3c7a702b10.png)

**Comment by EraChen233** [comment]
iOS-Tagent暂不支持xcode 11，再装一个xcode 10.2吧，一个Mac可以装多个版本xcode的

**Comment by luoting0323** [comment]
> iOS-Tagent暂不支持xcode 11，再装一个xcode 10.2吧，一个Mac可以装多个版本xcode的

好的，谢谢，我装一个试试。🌹

**Comment by luoting0323** [comment]
> iOS-Tagent暂不支持xcode 11，再装一个xcode 10.2吧，一个Mac可以装多个版本xcode的

 安装了xcode10版本之后，编译会报错，辛苦帮忙看下：
![image](https://user-images.githubusercontent.com/56343996/66638619-d9a7d980-ec47-11e9-9824-2c8576a0d68a.png)

**Comment by EraChen233** [comment]
iOS-Tagent 已更新，支持最新版xcode 11
